### ISSUE TITLE
Deploying Error (Error: Error when deploying:)

### ISSUE THREAD

**Issue by aidanoldershaw** [awslabs/chalice#103]
For a while, every other time I tried to deploy, I received the following error:

`Error: Error when deploying:`

No additional information was given. Occasionally, a different error message would appear, e.g. 

`Error: Error when deploying: list index out of range`

but deployment would generally work the second time around. Now, however, I get nothing but the first error, and cannot deploy at all. The contents of my config.json file are as follows:
```
{
  "manage_iam_role":false,
  "iam_role_arn": "arn:aws:iam::...:role/lambda_dynamo",
  "lambda_arn": "arn:aws:lambda:us-west-2:...:function:chalice_api",
  "app_name": "chalice_api",
  "stage": "dev"
}
```

**Comment by kishinmanglani** [comment]
Running into the same issue

**Comment by jamesls** [comment]
I'm trying to repro the issue but I'm not able to.  Do you have a specific set of steps that show the issue?  

Here's what I tried:

```
chalice new-project foo
chalice deploy
# (update the .chalice/config.json to match what you have, except I filled in my own iam_role_arn and lambda_arn)
chalice deploy
```

I'll see about adding more debug info on the error cases, but if someone can provide a set of steps that demonstrate the issue this would really help in resolving the issue.

**Comment by kishinmanglani** [comment]
This sort of fixed itself for me. A little while after commenting it worked. If I encounter the issue again, I'll try to figure out steps to repro

**Comment by Prefinem** [comment]
Also ran into this issue

    Initial creation of lambda function.
    Updating IAM policy.
    Creating deployment package.
    Error: Error when deploying:

**Comment by Merlineus** [comment]
I have the same issue
`
Initial creation of lambda function.
Updating IAM policy.
Creating deployment package.
Error: Error when deploying:
`

**Comment by hallazzang** [comment]
I tried to fix this issue, please check #124

**Comment by Prefinem** [comment]
@hallazzang It works now on my system.  Thanks!

**Comment by jamesls** [comment]
#124 has been merged, closing out issue.
