### ISSUE TITLE
Error: Unable to import your app.py file: numpy.dtype has the wrong size

### ISSUE THREAD

**Issue by loretoparisi** [awslabs/chalice#105]
I tried to deploy `numpy` package, my requirements file was like this

```shell
$ cat requirements.txt 
numpy>=1.11.1
scipy>=0.18.0
numpy>=1.11.1
scipy>=0.18.0
nltk>=3.2.1
scikit-learn>=0.17.1
empythy==0.5.6
```

$ sudo chalice deploy
Error: Unable to import your app.py file: numpy.dtype has the wrong size, try recompiling.

**Comment by loretoparisi** [comment]
So, this problem is not related to `chalice`, but I will keep the solution and close seems it's related to all python packages despite of `virtualenv` and that is the El Capitan System integrity protection:

```shell
$ csrutil status
System Integrity Protection status: enabled.
```

This protects the system against writing the `System` folder thus the Python packages as well installed before El Capitan through `sudo`. Now this is not possibile anymore, since El Capitan disabled the `root` user, so that you cannot do like

```shell
 $ sudo rm -rf /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy
```

to get rid of a previous version of let's say `numpy`.
So, you cannot just ignore installed packages like

```shell
$ sudo pip install --ignore-installed --upgrade numpy
```

The only solution that worked for me was to disable the SIP (restart Command+R, run in Utilities > Terminal):

```shell
$ crsutil disable; reboot
```

and then check if that worked:

```shell
$ csrutil status
System Integrity Protection status: disabled.
```

At this point you can finally upgrade your requirements and deploy with `chalice` (!)

```shell
sudo pip install --ignore-installed --upgrade -r requirements.txt
```

```shell
$ sudo chalice deploy
Initial creation of lambda function.
Creating role
Creating deployment package.
The directory '/Users/admin/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/admin/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Lambda deploy done.
Initiating first time deployment...
Deploying to: dev
https://xxxxxxxxxx.execute-api.us-east-1.amazonaws.com/dev/
```

Despite of some clues about `pip` library cache issues, it works in that way.
Using `virtualenv` did not help me, since `chalice` did not see the packages in the right path for some reason ( in the `env` folder).

**Comment by jamesls** [comment]
Thanks for digging into this.  One of the other issues you'll run into is that we don't have a way to support packages that require C bindings.  You need a version of that package that's built for linux.  I'll update our docs to state this limitation, but it is something I'm hoping we can address in the future.

Let me know if there's any other problems you're running into.
