### ISSUE TITLE
Deploy only Lambda (and support triggers)

### ISSUE THREAD

**Issue by gnardari** [awslabs/chalice#111]
Most of my lambda functions don't need API Gateway but the deployment automation that Chalice provides makes it still worth to use. I think this could be done in two parts:

- If no routes are found, deploy lambda only and the trigger setup is made afterwards by the user
- Fully support lambdas with different triggers e.g. S3, Dynamo

**Comment by toddrosner** [comment]
+1

**Comment by leoamigood** [comment]
+1
