### ISSUE TITLE
Raising Error Response Code yields JSON Not Serializable

### ISSUE THREAD

**Issue by Fabio101** [awslabs/chalice#112]
Hi Team

Firstly, I love this project, keep up the great work!

Writing a small Auth API and returning Error codes but getting the following error when testing the POST (The status code does return correctly though):

`{
"Code": "TypeError"
"Message": "UnauthorizedError('UnauthorizedError: Invalid Password',) is not JSON serializable"
}`

My full code is:

`@app.route('/login', methods=['POST'])
def login():
    request = app.current_request
    data = request.json_body

    email = data['email']
    password = data['password'].encode('utf-8')

    if email_validation(email) == True:
        #Check if the Valid Email Already Exists in order to login
        try:
            if user_exists(email) == True:
                response = table.query(
                    KeyConditionExpression=Key('email').eq(email)
                )
                #Determine if the provided password matches the hashed password
                if hashpw(password, response['Items'][0]['password'].encode('utf-8')) == response['Items'][0]['password']:
                    return {'Success': 'User Authenticated'}
                else:
                    raise UnauthorizedError('Invalid Password')
        except Exception as e:
            return e
        else:
            raise NotFoundError('Email is not Registered')
    else:
        raise ForbiddenError('Invalid or Non-Existent Emaill Address')`

Am I doing something wrong? Or is this just me?

**Comment by jamesls** [comment]
Seems like it could be related to https://github.com/awslabs/chalice/issues/113, which is fixed via https://github.com/awslabs/chalice/pull/114.  Let me double check on this.

**Comment by jamesls** [comment]
Oh, another thing I noticed, you have:

```
        except Exception as e:
            return e
```

which is what's actually causing you're issue here.  If you return something, it has to be json serializable.  But in this case, if you just want the exception to propagate, you should `raise` the exception instead of returning it.  If you change that to `raise e`, then once #114 is merged in you should be all set.

**Comment by jamesls** [comment]
#114 has been merged so if you pull the latest master branch, you should be all set (I'd like to get a release out soon but don't have a definite date yet).

If you're still seeing issues, let me know and I'll reopen and take another look.

**Comment by Fabio101** [comment]
Thanks for the advice!

This is working great now, using raise instead of return and having merged #114
