### ISSUE TITLE
Any exceptions result in ChaliceViewError

### ISSUE THREAD

**Issue by theemadnes** [awslabs/chalice#113]
Trying to test BadRequestError via the following code:

```
from chalice import Chalice
from chalice import NotFoundError, BadRequestError
import time
import random

app = Chalice(app_name='demoChalice')


@app.route('/')
def index():

    raise BadRequestError("error message")

    return {'hello': 'world'}`
```
I would expect to receive a 400 error, but all I get is:

`{"Code": "ChaliceViewError","Message": "ChaliceViewError: An internal server error occurred."}`

**Comment by theemadnes** [comment]
Code markup is a bit messed up, but hopefully the issue is understandable.

**Comment by jamesls** [comment]
Confirmed, the exception only propagates if `app.debug = True` is set.  Working on a fix.
