### ISSUE TITLE
Package on PyPi not in sync with Github

### ISSUE THREAD

**Issue by Malimediagroup** [awslabs/chalice#121]
When deploying, I get:
`Error: Unable to import your app.py file: cannot import name UnauthorizedError`

Because, in `__init__.py` in the pip-package, lno. 2:
```python
from chalice.app import ChaliceViewError, BadRequestError, NotFoundError
```

In `__init__.py` on Github (https://github.com/awslabs/chalice/blob/c9bef0c4e7d1aa6bb8f8bb3df110c52dc91e5798/chalice/__init__.py#L2-L5):
```python
from chalice.app import (
    ChaliceViewError, BadRequestError, UnauthorizedError, ForbiddenError,
    NotFoundError, ConflictError, TooManyRequestsError
)
```

**Comment by jamesls** [comment]
I'd like to get a few more changes together, I'll be getting a pypi release out shortly.

**Comment by jamesls** [comment]
I was hoping to get CORs support in this release, but it's going to take a little more time and I'd prefer to get all the bug fixes pushed sooner rather than later.  pypi now has version `0.2.0` release which includes the fix for the issue your'e seeing.
