### ISSUE TITLE
requirements.txt only gets picked up on initiall "chalice deploy"

### ISSUE THREAD

**Issue by colwilson** [awslabs/chalice#127]
- create a default app
- add import whois to app.py
- add whois to requirements.txt
- run chalice deploy

`Error: Unable to import your app.py file: No module named whois
`

does not seem to pick up the requirements or the docs do not explain how to do that.

**Comment by jamesls** [comment]
I'm having trouble repro'ing the issue.  I followed the same steps you outlined above:

**Create default app**
```
$ chalice new-project testdeps
$ cd testdeps/
$ ls
app.py           requirements.txt
$ chalice deploy
Initial creation of lambda function.
Creating role
Creating deployment package.
Lambda deploy done.
Initiating first time deployment...
Deploying to: dev
https://rest-api-id.execute-api.us-west-2.amazonaws.com/dev/
$ http https://rest-api-id.execute-api.us-west-2.amazonaws.com/dev/
HTTP/1.1 200 OK

{
    "hello": "world"
}

```

**Add import whois to app.py and update requirements.txt**

```
$ pip install whois
Collecting whois
Installing collected packages: whois
Successfully installed whois-0.7
# Updated requirements.txt
$ cat requirements.txt
whois==0.7

# Updated app.py
$ cat app.py
from chalice import Chalice
import whois

app = Chalice(app_name='testdeps')


@app.route('/')
def index():
    return {'whois': 'module: %s' % whois}
```

**Run chalice deploy**

```
$ chalice deploy
Updating IAM policy.
Updating lambda function...
Creating deployment package.
Not overwriting existing python script ...
Sending changes to lambda.
Lambda deploy done.
API Gateway rest API already found.
Deleting root resource id
Done deleting existing resources.
Deploying to: dev
https://rest-api-id.execute-api.us-west-2.amazonaws.com/dev/
$ http https://rest-api-id.execute-api.us-west-2.amazonaws.com/dev/
HTTP/1.1 200 OK

{
    "whois": "module: <module 'whois' from '/var/task/whois/__init__.py'>"
}

```

Does that look about the same as what you were doing?

**Comment by colwilson** [comment]
This isn't clear in the docs I think.

When I do "pip install whois" I'm not in a virtualenv so installing anything can only install globally. Have I missed something? How could Chalice know about it?

**Comment by jamesls** [comment]
When you run "chalice new-project", it will create a `requirements.txt` file next to the `app.py`.  That's the file it uses to figure out which dependencies to include when deploying (via `pip install -r requirements.txt`).  You do raise a good point that this isn't very clear and only briefly mentioned in the docs.  I'll get that updated.

**Comment by colwilson** [comment]
Ok thanks I finally get it, and got it to work for me.

These are the notes I took (for linux) maybe they will help others:

```
# create a virtualenv with chalice installed
mkdir chalice-projects
cd chalice-projects/
virtualenv .
source ./bin/activate
pip install chalice

# create a new project
chalice new-project requirements-demo
cd requirements-demo/

# install required modules
pip install whois
# add them to requirements so they will be installed remotely
pip freeze | grep whois > requirements.txt

# write the app
cat << EOF > app.py
from chalice import Chalice
import whois

app = Chalice(app_name='helloworld')

@app.route('/')
def index():
    return {'whois': 'module: %s' % whois}

EOF

# deploy
chalice deploy

# test the endpoints
curl https://tbx8yv9852.execute-api.us-east-1.amazonaws.com/dev/

{"whois": "module: <module 'whois' from '/var/task/whois/__init__.py'>"}

```

**Comment by Regner** [comment]
Seems this issue can probably be closed?

**Comment by andriisoldatenko** [comment]
@jamesls do we need update docs with this example?

**Comment by noahgift** [comment]
Hi,

I was also bit by this and wondering the canonical way you would recommend including code that isn't a pip package?  For example, the deploy seems to assume all source code lives in app.py, but you may have a library, with private source code (not on pypip), that you may to include in the project.

Personally, I like with lambda projects to include the source and app.py inside of a build process versus getting into creating a setup.py and using pip with version numbers.  Here is an example of how I did this on another lambda I created:  https://gist.github.com/noahgift/4bdad190724047a088632676faba34f1.

**Comment by kadrach** [comment]
@noahgift I believe you are looking for [multifile support].(http://chalice.readthedocs.io/en/latest/topics/multifile.html)

**Comment by noahgift** [comment]
@kadrach thanks this is great to know. I must have missed this and it goes a long way.  Still what is missing to me is the best way to include a common util library.  For example in the structure below, there isn't an easy way to put a common library (used outside of chalice) into "chalice deploy".  Initially, I created a setup.py that I then referenced via requirements.txt:  1 file://../.  The is issue then is that as this thread alludes to is that only on initial deploy does my library get packaged.  So I cannot use this for development without forking "chalice deploy" and making it create a "fresh" deploy each time, or just making my own deploy.

(benv) ➜  tree example 
example
├── chalice_app
└── lib

**Comment by noahgift** [comment]
In thinking about this more, the "hack" is I can call "chalice deploy" in a makefile and I can create a build step where I cp -r my lib into chalicelib.  So thanks @kadrach this led me down the right path.  What I was looking for was a way to get something into a location where it would get zipped and sent to the lambda directory.  Might be good to make this support more explicit and/or document it though, since this going to be a very common use case.  I.E you have a single github repo with a shared library where there are other tools that use the library and you want to deploy parts of shared library to a chalice app.

**Comment by noahgift** [comment]
Ok, verified this approach works.  I created a makefile with this:

`deploy-api:
	rm -rf api/chalicelib/uca; cp -r uca api/chalicelib/
	@cd api; chalice deploy`

Then my app looks like this:

`import json

import logging
log = logging.getLogger()
log.setLevel(logging.INFO)

from chalice import Chalice
from chalicelib import uca

app = Chalice(app_name='api')

@app.route('/')
def index():
    route_msg = {"route": "/", "version": uca.__version__}
    log.info(json.dumps(route_msg))
    return {'hello': 'world'}
`

When I deploy, I used json logging to verify import works:

`(ucpyenv) ➜  lumRENDER git:(master) ✗ awslogs get /aws/lambda/api --query="version" -s1d 
/aws/lambda/api 2017/02/02/[$LATEST]a8faaad988d049daaf485c90355a82d4 START RequestId: 8c6107e3-e985-11e6-8b7d-2fd08d2d5912 Version: $LATEST

/aws/lambda/api 2017/02/02/[$LATEST]a8faaad988d049daaf485c90355a82d4 [INFO]	2017-02-02T20:24:07.980Z	8c6107e3-e985-11e6-8b7d-2fd08d2d5912	{"route": "/", "version": "0.5"}

/aws/lambda/api 2017/02/02/[$LATEST]a8faaad988d049daaf485c90355a82d4 END RequestId: 8c6107e3-e985-11e6-8b7d-2fd08d2d5912

/aws/lambda/api 2017/02/02/[$LATEST]a8faaad988d049daaf485c90355a82d4 REPORT RequestId: 8c6107e3-e985-11e6-8b7d-2fd08d2d5912	Duration: 0.50 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 8 MB	

/aws/lambda/api 2017/02/02/[$LATEST]a8faaad988d049daaf485c90355a82d4 START RequestId: 94b889e3-e986-11e6-af71-17e6562de6e8 Version: $LATEST

/aws/lambda/api 2017/02/02/[$LATEST]a8faaad988d049daaf485c90355a82d4 [INFO]	2017-02-02T20:31:31.165Z	94b889e3-e986-11e6-af71-17e6562de6e8	{"route": "/", "version": "0.5"}

/aws/lambda/api 2017/02/02/[$LATEST]a8faaad988d049daaf485c90355a82d4 END RequestId: 94b889e3-e986-11e6-af71-17e6562de6e8

/aws/lambda/api 2017/02/02/[$LATEST]a8faaad988d049daaf485c90355a82d4 REPORT RequestId: 94b889e3-e986-11e6-af71-17e6562de6e8	Duration: 0.55 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 8 MB	
`

**Comment by jamesls** [comment]
There's been a significant overhaul in how we package applications.  In addition to chalicelib, you also have a `vendor/` directory you can use.  We've created a topic guide in our docs that does into this in more detail here: http://chalice.readthedocs.io/en/latest/topics/packaging.html

Let us know if you have any more questions.
