### ISSUE TITLE
Content-Type lookup is case sensitive

### ISSUE THREAD

**Issue by chrisgilmerproj** [awslabs/chalice#129]
Using `fetch()` method from javascript and it does a lowercase operation before it send out my header.  That means `Content-Type` becomes `content-type`.

This problem was noted in the code already:

https://github.com/awslabs/chalice/blob/master/chalice/app.py#L72-L75

Turns out this problem happened recently with the addition of 1a2ae877e0708be8a046c90e194908f414adb1fa.

I suggest just checking for both:

```py
if self.headers.get('Content-Type') == 'application/json' or \
        self.headers.get('content-type') == 'application/json' :
    self.json_body = body
```

Headers should be case-insensitive, so perhaps the class should lowercase all the headers as it reads them?

**Comment by jamesls** [comment]
Closing, https://github.com/awslabs/chalice/pull/130 has been merged.

**Comment by chrisgilmerproj** [comment]
Thanks so much for the work on this!
