### ISSUE TITLE
Chalice doesn't support dict comps

### ISSUE THREAD

**Issue by RogerThomas** [awslabs/chalice#131]
Dict comps break ``chalice deploy`` with awfull error messagas

e.g. this anywhere in the code will cause ``chalice deploy`` to fail
```python
d = {k: v for k, v in [(1, 2), (3, 4)]}
```
I know dict  comp's were only introduced in 2.7, but I thought chalice was 2.7>

**Comment by jamesls** [comment]
Definitely a bug, you should be able to use dict comprehensions in a chalice app.  I'll get that updated.
