### ISSUE TITLE
Boto3 resource types support in policy generation

### ISSUE THREAD

**Issue by BenWal** [awslabs/chalice#132]
Chalice ignores usage of boto3's resource types when generating IAM policies. Yes, I can just use botocore directly, but I like the resource interfaces and I'd like to be able to use them in chalice easily.

**Comment by jamesls** [comment]
This is something I'd like to add.  Marking as a feature request.

**Comment by jamesls** [comment]
I missed this earlier, but there's a pre-existing feature request for this: https://github.com/awslabs/chalice/issues/118

Consolidating issues.
