### ISSUE TITLE
Deploy with --no-autogen-policy errors with EntityAlreadyExists message

### ISSUE THREAD

**Issue by theemadnes** [awslabs/chalice#139]
When deploying against an existing Chalice app, I get the following error when using the --no-autogen-policy:

```
chalice deploy --no-autogen-policy
Creating role
Error: Error when deploying: An error occurred (EntityAlreadyExists) when calling the CreateRole operation: Role with name #chalice_project_name# already exists.
```

I have to manually delete the IAM role to get ```chalice deploy``` to work.

**Comment by tiyberius** [comment]
I am also having this problem, but not even passing `--no-autogen-policy`

**Comment by tiyberius** [comment]
Created a pull request to address the issue. @theemadnes maybe you can test it? https://github.com/awslabs/chalice/pull/141

**Comment by jamesls** [comment]
#141 has been merged, this fix is now available in the master branch.  Let me know if you're still running into issues.
