### ISSUE TITLE
Need a way to handle auth

### ISSUE THREAD

**Issue by garnaat** [awslabs/chalice#14]
AFAICT, there is currently no way to get any kind of authentication of requests.

**Comment by daneah** [comment]
Are you referring to basic HTTP authentication? I could imagine building OAuth into your API with the existing functionality, but I could be missing something 😄

**Comment by JamieCressey** [comment]
API Gateway supports;
1) API Key
2) IAM User signature
3) Custom auth

Custom Auth being a lambda function which manages OAuth or any other authentication mechanism not defined above. 

I believe enabling 1) and 2) are just additional variables to pass within the API request so shouldn't be too difficult to do.

**Comment by mnhcorp** [comment]
I've tried API Keys and they work fine once I set them manually (after `chalice deploy`)

Every time I re-deploy with `chalice deploy --no-autogen-policy` it overwrites my API key settings. 
Is that a bug?
