### ISSUE TITLE
chalice deploy -- Local command

### ISSUE THREAD

**Issue by jonmcoe** [awslabs/chalice#151]
Remote deploy works well, but my local command does this (helloworld is the directory):

```
(chalice) ➜  helloworld chalice local
Local command
chalice) ➜  helloworld chalice local
Local command
(chalice) ➜  helloworld pip freeze
botocore==1.4.67
chalice==0.3.0
click==6.2
docutils==0.12
jmespath==0.9.0
python-dateutil==2.5.3
requests==2.11.1
six==1.10.0
typing==3.5.1.0
virtualenv==15.0.3
```

**Comment by jamesls** [comment]
The `chalice local` command is only available in the master branch right now.  The previous version was just a placeholder command.  I plan on getting a release out shortly that will include this functionality.

**Comment by jonmcoe** [comment]
thanks for the prompt response, and sorry i didn't read the changelog before opening the issue.

i see this placeholder in the my site-packages 0.3.0 now:
```
@cli.command()
@click.pass_context
def local(ctx):
    click.echo("Local command")
```

looking forward to the next release! have been really impressed with how easy this is to use

**Comment by sellers** [comment]
If you want to play with this feature - you can git clone the master branch, and then cd {git_clone_location} and then  `easy_install --user .`    and it will make it available.       That --user puts it in your local path (useful on macos(x) systems)
