### ISSUE TITLE
importing `requests` library causes `"Unable to import module 'app'"` error

### ISSUE THREAD

**Issue by dt4k** [awslabs/chalice#153]
Below works fine. 
```
@app.route('/')
def index():
    return {'hello': 'world'}
```

and this fails. In my code, I'd like to hit more request inside a lambda function.

```
import requests
@app.route('/')
def index():
    return {'hello': 'world'}
```

deploying this, trying request causes "unable to import module app" error whatever the other method is.

```
{
    "errorMessage": "Unable to import module 'app'"
}
```

**Comment by jamesls** [comment]
Do you have requests listed in your requirements file?   If not you'll need to have:

```
$ pip install requests
$ pip freeze > requirements.txt
```

**Comment by dt4k** [comment]
Oops, it did the trick. Thanks!
