### ISSUE TITLE
Unable to import your app.py file: No module named boto3

### ISSUE THREAD

**Issue by onurmatik** [awslabs/chalice#155]
I have a simple code to write files to AWS S3 using boto3 S3 client. boto3 is installed into the virtual environment and is in the requirements.txt along with a few other required packages. I can import it and other packages with no problem locally. I can run the code via shell. But when I try to deploy I get an import error:

    $ chalice deploy
    Error: Unable to import your app.py file: No module named boto3

**Comment by jamesls** [comment]
I'm not able to repro.  Here's what I tried:

```
( in a new virtualenv)
$ pip install chalice
$ pip install boto3
$ chalice new-project boto3-import
$ cd boto3-import/
$ echo 'boto3==1.4.1' > requirements.txt
$ cat requirements.txt
boto3==1.4.1
$ cat app.py
from chalice import Chalice
import boto3

app = Chalice(app_name='boto3-import')


@app.route('/')
def index():
    return {'boto3-file': boto3.__file__}

$ chalice deploy
$ http https://01xt03f9ph.execute-api.us-west-2.amazonaws.com/dev/
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 45
Content-Type: application/json
...

{
    "boto3-file": "/var/task/boto3/__init__.py"
} 
```

Can you double check that the virtualenv that you're running the `chalice deploy` command has boto3 installed?

**Comment by onurmatik** [comment]
Sorry, my bad. It was a different virtualenv with boto3 installed but not chalice I was trying to run the deploy command. I was confused because I was seeing boto3 in the environment and I was being able to import it via python shell. It went through this time. Thank you for your time.
