### ISSUE TITLE
Add support for optional deployment options

### ISSUE THREAD

**Issue by wscoble** [awslabs/chalice#192]
Specifically, I would like to see deployment options in the config.json file to handle timeout and memory size.

I will work on a PR for this feature request as well.

**Comment by wscoble** [comment]
Actually, this seems to be supported, just not documented yet.

**Comment by kyleknap** [comment]
Support for configuration of lambda function timeout and memory size was completed in this merged PR: https://github.com/awslabs/chalice/pull/351 under this proposal: https://github.com/awslabs/chalice/issues/347. Closing out issue.
