### ISSUE TITLE
Passing query params breaks route in local

### ISSUE THREAD

**Issue by atomaka** [awslabs/chalice#196]
When using `chalice local`, a route will not match if parameters are passed via the query string.

Given:
```
from chalice import Chalice

app = Chalice(app_name='web')

@app.route('/')
def index():
    name = app.current_request.query_params.get('name')
    return {'hello': name}
```

Running `chalice local` and then visiting `http://localhost:8000/?name=test` will result in `ERR_EMPTY_RESPONSE` with an error tracing back to `raise ValueError("No matching route found for: %s" % url)`.

Running `chalice  deploy` and then visiting the provided URL functions as expected and will return `{"hello": "test"}`.

**Comment by jamesls** [comment]
Fixed via https://github.com/awslabs/chalice/pull/184
