### ISSUE TITLE
Can't POST after deploying simple app with Chalice

### ISSUE THREAD

**Issue by pcolmer** [awslabs/chalice#199]
I've written a very simple test for Chalice that looks like this:

    import sys
    import logging
    
    from chalice import Chalice
    
    app = Chalice(app_name='service-desk-automation')
    app.log.setLevel(logging.DEBUG)
    app.debug = True
    
    @app.route('/')
    def index():
        app.log.debug("Hello world called")
        return {'hello': 'world'}
    
    @app.route('/v1/forgotten-password', methods=['PUT'])
    def forgottenpassword():
            app.log.debug("Forgotten password webhook called")
            request = app.current_request
            event = request.json_body
            app.log.debug(event)

            return {}

However, I'm struggling to understand what the correct URL should be to try POSTing to the app. Chalice says that the URL is:

https://XXXXXXXXXX.execute-api.us-east-1.amazonaws.com/dev/

When I try:

curl -H "Content-Type: application/json" -X POST -d @ServiceDeskTicket.json https://XXXXXXXXXX.execute-api.us-east-1.amazonaws.com/dev/v1/forgotten-password

I get "Missing Authentication Token".

When I try:

curl -H "Content-Type: application/json" -X POST -d @ServiceDeskTicket.json https://XXXXXXXXXX.execute-api.us-east-1.amazonaws.com/dev/v1/forgotten-password

I get "Forbidden".

If I go to the API Gateway and use the test feature there to paste the JSON content and run the PUT, the Lambda code works, so it seems like I've either got something misconfigured on the API gateway or I'm using the wrong URL or ... ?

Thanks.

Philip

**Comment by liampauling** [comment]
Your method is PUT but you are making a POST request, or am I missing something?

**Comment by andriisoldatenko** [comment]
`curl -H "Content-Type: application/json" -X PUT -d @ServiceDeskTicket.json `
try something like this or add `POST`
`@app.route('/v1/forgotten-password', methods=['PUT', 'POST'])`

**Comment by pcolmer** [comment]
Thank you, both. It was indeed my mistake and the code should have been ['POST'] instead of PUT.

Apologies for the noise.
