### ISSUE TITLE
Parse raw_body to get file from multipart/form-data

### ISSUE THREAD

**Issue by meteorza** [awslabs/chalice#200]
Using dropzone.js to upload files from the browser to API Gateway and S3. Used the default multipart/form-data content-type. 

How would I parse the raw_body to get the filename and file content to PUT to S3? 

urlparse.parse_qs not providing the desired result when using multipart/form-data

It seems Flask has a request.files object property to extract the file content from the body. Could this be included as a new feature perhaps? Or is there another way to parse the raw_body?

**Comment by meteorza** [comment]
Not to worry. Just seen that API Gateway has a limit of 10MB payload, so uploads through API Gateway and Lambda to S3 is not the ideal way to do this. It seems I have to stay with uploading to S3 directly.

**Comment by jsanchezs** [comment]
I would like to reopen this issue. There is not way to parse multipart/form-data =/
