### ISSUE TITLE
Debugging application when running local

### ISSUE THREAD

**Issue by arundhaj** [awslabs/chalice#215]
Is there an approach to debug (apart from logging) chalice application with breakpoints. I use Eclipse IDE with PyDev.

**Comment by ButtaKnife** [comment]
The chalice script itself is just a Python script.  You can run/debug right from there.

**Comment by andriisoldatenko** [comment]
@arundhaj 
Try to learn `pdb` or `pip install ipdb`:

```
(chalice-2.7.13) ➜  helloworld chalice local
Serving on localhost:8000
> /Users/andrii/work/awslabs/helloworld/app.py(9)index()
      7 def index():
      8     import ipdb; ipdb.set_trace()
----> 9     return {'hello': 'world'}
     10
     11
ipdb>
```

**Comment by jamesls** [comment]
Hi, as mentioned, you can just debug the python script either via pdb or by setting breakpoints in your IDE.  There's a suggestion for this in [pycharm here](https://github.com/awslabs/chalice/pull/216#issuecomment-270355138).  You could probably adapt that for Eclipse as well.

Let me know if you have any more questions.
