### ISSUE TITLE
Response content types

### ISSUE THREAD

**Issue by byumark** [awslabs/chalice#218]
Looks like specifying input content types was added at some point. Would it be possible to specify output content types? Or is it already possible? I was playing around with the idea of returning 'text/html' just for fun. Can't think of other use cases right now.

**Comment by jamesls** [comment]
The latest version of 0.6.0 now makes this possible.  The default JSON response is still preserved, but you can return a [chalice.Response](http://chalice.readthedocs.io/en/latest/quickstart.html#tutorial-customizing-the-http-response) instance which allows you to specify custom headers including content type:

```python
from chalice import Chalice, Response

app = Chalice(app_name='custom-response')


@app.route('/')
def index():
    return Response(body='hello world!',
                    status_code=200,
                    headers={'Content-Type': 'text/plain'})
```

The only caveat to be aware of is that binary content still isn't supported.  API Gateway requires some additional work to configure which content types are binary (https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings.html).  I do have this on my backlog of features, but your example of `text/html` will now work.

Let me know if you have any questions/feedback about this feature.

**Comment by bensiu** [comment]
Is it possible to extend this functionality to support other return types like application/pdf ?

Problem has been described in question http://stackoverflow.com/questions/42906859/use-aws-chalice-to-generate-pdf

**Comment by BigChief45** [comment]
@bensiu I took a look at your SO question and I am experiencing a very similar situation. Did you find any solution to it?
