### ISSUE TITLE
compatibility with more complex Flask applications?

### ISSUE THREAD

**Issue by gliptak** [awslabs/chalice#221]
I tried to run https://github.com/pallets/flask/tree/master/examples/flaskr/flaskr example under Chalice. I created the database and started the app under flask. After renaming ```flaskr.py``` to ```app.py``` (unmodified), hitting ```http://localhost:8000/``` shows:

```
$ chalice local
Serving on localhost:8000
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 36198)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/user/.local/virtualenvs/flask/local/lib/python2.7/site-packages/chalice/local.py", line 120, in __init__
    RouteMatcher(list(app_object.routes)))
AttributeError: 'Flask' object has no attribute 'routes'
----------------------------------------
```

Modifying ```app.py``` to

```
app = chalice.Chalice(app_name=__name__)
```

shows to error:

```
$ chalice local
Error: Unable to import your app.py file: 'Chalice' object has no attribute 'config'
```

Applications with Flask extensions might experience other problems.

Did I miss some configuration steps? Is there suggested way to accomplish this?

Please let me know if this is a non-goal (as I might have missed this stated in the docs).

Thanks

**Comment by stealthycoin** [comment]
Im not sure exactly what you are trying to do, I'm not that familiar with Flask but Im assuming you are trying to turn a Flask app into a Chalice app?

Assuming this is what you are trying to do. Chalice is its own framework it doesn't have any compatibility with flask, they both are simple and used for similar things so there may be some superficial similarities. So, you should not be able to simply make a few changes to a Flask app and turn it into a Chalice app.
