### ISSUE TITLE
Add `--port port-number` option to `chalice local`

### ISSUE THREAD

**Issue by jamesthiele** [awslabs/chalice#225]
The `chalice local` command is hardwired to serve on port 8000 (see source file `local.py`). Adding a `--port port-number`  option would avoid potential conflicts and allow multiple chalice lambda functions to be debugged locally.

**Comment by andriisoldatenko** [comment]
Please check this PR awslabs/chalice/pull/220/files

**Comment by jamesthiele** [comment]
Sorry, this is a duplicate of issue #220.
