### ISSUE TITLE
Support for Proxy Integration for a Proxy Resource

### ISSUE THREAD

**Issue by wobeng** [awslabs/chalice#226]
Any support for  Proxy Integration for a Proxy Resource? 

[http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-lambda.html](url)

**Comment by joevandyk** [comment]
i'd like to know as well.

**Comment by jamesls** [comment]
Could you tell me more about how you'd use this?

I've been looking into making this change, but primarily as an internal refactoring to remove all the VTL mappings I'm using currently.  However, switching to proxy integration would mostly be a transparent change for users.

**Comment by jamesls** [comment]
I've implemented this here: https://github.com/awslabs/chalice/pull/240

One of the nice things about this approach is that you can now return a custom `Response` instance if you want complete control over the HTTP body/headers/status code

**Comment by jamesls** [comment]
Closing, this is now available to v0.6.0 of chalice.
