### ISSUE TITLE
Support for egg-links

### ISSUE THREAD

**Issue by jleclanche** [awslabs/chalice#227]
When installing a dependency with git that is marked as zip-safe, `egg-link` files are created instead of a folder.

Chalice does not handle this. 

https://github.com/awslabs/chalice/blob/79560c81764f2a341daa729b3511513bd6a944cd/chalice/deployer.py#L397-L426

Zappa supports it:

https://github.com/Miserlou/Zappa/blob/f34beb51c2d7d0932769ccd54498010f47a36041/zappa/zappa.py#L394-L400

**Comment by jamesls** [comment]
#388 added support for this.  We've rewritten how we handle dependencies and egg links are automatically supported now.
