### ISSUE TITLE
Using custom authorizers locally

### ISSUE THREAD

**Issue by joevandyk** [awslabs/chalice#228]
I'm relying on a custom authorizer to pass along some data about the user making the request. 

This works fine on production but I can't seem to find a way when running chalice locally to pass along the data in the context object. 

Is this possible?

**Comment by stealthycoin** [comment]
@joevandyk Ah I'm sorry I didn't see this one earlier. I opened a feature request for this here:
https://github.com/awslabs/chalice/issues/404 

I'm going to close this issue and track that feature in the other issue. You are correct in that it is currently not possible, but its something we would like to add.
