### ISSUE TITLE
Multiple Lambdas in 1 Chalice project

### ISSUE THREAD

**Issue by honzous** [awslabs/chalice#229]
Could we choose if we want to deploy 1 big function (current way) or to deploy separate functions for each routing definition? This could save resources and improve execution times for more robust projects.

**Comment by TronPaul** [comment]
It would also be helpful to be able to deploy non-chalice lambdas as well, ie custom authorization lambdas, during chalice deployment.

**Comment by frob** [comment]
I thought this could be done with endpoint variables? Take a look at the docs for [addition routing](http://chalice.readthedocs.io/en/latest/quickstart.html#tutorial-additional-routing)

**Comment by jamesls** [comment]
It's now possible to deploy non-chalice lambda for custom authorizers as well as scheduled events, but we still use one lambda function for the API handler.

However, deploying as separate functions is going to be difficult at this point.  There's some assumptions baked into chalice's deployment process that assumes there's one lambda function as the API handler.

I'm going to mark this as out of scope for now, but if people want this please feel free to comment/+1 the issue and share your use case.

**Comment by rajasimon** [comment]
I was reading the [purelambda](http://chalice.readthedocs.io/en/latest/topics/purelambda.html) documentation.  And it's very clear that I can able to create multiple lambda functions. But how do trigger that lambda functions? 

In the below example when I call the api gateway resource `/` I wanted to trigger the `custom_lambda_function` in some point. 

```

@app.lambda_function()
def custom_lambda_function(event, context):
    # Anything you want here.
    return {}

@app.route('/')
def index():
    custom_lambda_function(args) <--- Shall I call the other lambda functions like this ?
    return {'hello': 'world'}

```

**Comment by advaer** [comment]
+1. For now I use separate chalice apps to keep lambdas not so huge.

**Comment by luisdemarchi** [comment]
My project with Chalice, is 9 routes. And the total size (with libraries) is at 22 MB. I think it would be extremely useful if  could separate into more lambdas.

**Comment by luisdemarchi** [comment]
@advaer How do you maintain the same API gateway?

**Comment by gmachado-janrain** [comment]
+1 separate lambdas

**Comment by eallais** [comment]
+1
Any updates?

**Comment by pdyba** [comment]
+1 for separate lambdas
Any updates?

**Comment by RahulChowdaryN** [comment]
+1 for configuring separate lambdas

**Comment by Cyb-himanshu** [comment]
+1 seperate lambdas 
to check every lambda

**Comment by mikaelagoldrich** [comment]
+ 1 for separate lambdas

**Comment by c4road** [comment]
+1 for separate lambdas and a seamless way to get all the info needed for any cdk construct attachment

**Comment by sigoulder** [comment]
+1 for separate lambdas. Siloing lambdas that share implementation / config / modules into separate chalice apps causes a maintainability / duplication nightmare.

**Comment by WiWhite** [comment]
+1 for separate lambdas

**Comment by erdem** [comment]
+1

**Comment by Fgabz** [comment]
+1

**Comment by j-adamczyk** [comment]
+1, currently the only way is separating the project into multiple Chalice apps, which is pretty terrible

**Comment by Vvaradinov** [comment]
+1

**Comment by Riz-waan** [comment]
+1

**Comment by Matvii-Boichenko** [comment]
+1

**Comment by zephyrosjyd** [comment]
+1

**Comment by tomdiinur** [comment]
+100

**Comment by daddepledge** [comment]
+ 1

**Comment by JDeanThomas** [comment]
+1

**Comment by akuma5157** [comment]
+1

**Comment by nineclicks** [comment]
+1 I have one endpoint that needs an elevated amount of RAM but the rest do not, it would be helpful to be able to give those heavier endpoints a different lambda to work in.

**Comment by mariovalney** [comment]
+1 (and thanks for chalice)

**Comment by fpp-akhil** [comment]
+1

**Comment by mall0xc** [comment]
+1
