### ISSUE TITLE
Docs about how this compares to a bare python aws lambda implementation

### ISSUE THREAD

**Issue by gpip** [awslabs/chalice#23]
After reading the docs I couldn't tell if it's possible to do the following or not, so maybe this is a matter of updating the docs to further clarify what is possible. So, before this framework came to existence I would deal with S3 updates by uploading a new aws lambda like this:

```
	aws lambda create-function --region someregion --function-name somename \
		--zip-file fileb://./somefile.zip --role somerole \
		--handler somename.handler --runtime python2.7 --profile default \
		--timeout 5 --memory-size 128
```

and then grant a permission related to S3:

```
	aws lambda add-permission --region someregion --function-name somename \
		--action "lambda:InvokeFunction" --principal s3.amazonaws.com \
		--source-arn somearn --source-account someacc --profile default \
		--statement-id someperm
```

`somename.handler` would contain something like:

```
def handler(event, context):
    for record in event['Records']:
        bucket = record['s3']['bucket']['name']
        key = record['s3']['object']['key']
    ...
```

Now, using chalice how would I implement that `handler` function that receives information about objects created on S3? Is it possible/trivial to do it here?

**Comment by jamesls** [comment]
Chalice doesn't support event sources.  It's really only designed to pair with API gateway to set up a rest API.  It may be something we'd consider in the future, but there's no immediate plans to support this.

**Comment by gpip** [comment]
I see :/  This made using aws lambda a lot more convenient, looking forward to a later version that supports this use case. Thank you
