### ISSUE TITLE
Unable to import module 'app': /var/task/psycopg2/_psycopg.so: invalid ELF header 

### ISSUE THREAD

**Issue by mooresm139** [awslabs/chalice#232]
Hi,

I am trying to connect to a postgres RDS database instance using psycopg2.  However, I get this error when the app.py tries to import psycopg2.  In addition to trying with a regular pip install psycopg2 on a mac, I compiled a version on amazon linux and got this error when I included it in the site libraries directory under .chalice.  Both tries resulted in the same error, invalid ELF header in _psycopg.so, seen in the CloudWatch logs for the app.  Is there any experience with this happening?  What can I do to try and fix it?

**Comment by MaxMargolis** [comment]
I have this problem as well. Did you ever figure it out?

**Comment by mooresm139** [comment]
No, not yet.  Thinking of taking the DynamoDB route and creating a DB table in there to use since it is already built into boto3. That way I won’t have to use psycopg2.

Samantha Moore  | Systems Engineer (O) 310.760.8328 | (M) 310.699.0445
Sony DADC New Media Solutions | 4499 Glencoe Ave. | Marina del Rey, CA 90292  P Operation Green - Please Think Before Printing

**Comment by MaxMargolis** [comment]
I've been reading that you have to build your virtualenv on an Amazon Linux AMI as detailed here:

[http://davidhamann.de/2017/01/27/import-issues-running-python-aws-lambda/](url)

**Comment by mooresm139** [comment]
Have you come across anything useful?

**Comment by MaxMargolis** [comment]
Mostly I've read to build a virtualenv on an Amazon Linux AMI. I see you tried that already. This is an interesting thread as well:

[https://forums.aws.amazon.com/thread.jspa?messageID=762287&#762287](url)

**Comment by jamesls** [comment]
So the best option for now is going to be https://github.com/awslabs/chalice/pull/182

It's been merged into the master branch and will be in a release shortly.  The idea is that you'd download the linux specific binary into that directory, and then chalice will automatically include that in the deployment package.  I'll update the docs with an example of how to do this for psycopg2

The long term goal though is to automatically "just work".  When chalice see's psycopg2 in a requirements.txt file it knows to somehow pull in the linux specific binary regardless of what platform you're developing on.  Not sure on the timeline on that, there's still a few unresolved issues I need to figure out.

**Comment by jamesls** [comment]
I added an example of how you can use the `vendor/` directory to use `psycopg2` in an app.  This isn't released yet, so if you wanted to try it out until then you can use the `master` branch.

Let me know if you have any more questions.

**Comment by jarikujansuu** [comment]
Any idea when this could be released? I have same problem with cryptography or pycrypy package that I need to read JWT token for Firebase. Just thinking if it days or max 2 weeks I could easily do some hack solution, but if it is longer I have to think what to do.
