### ISSUE TITLE
Importing the multiarray numpy extension module failed

### ISSUE THREAD

**Issue by baileyspace** [awslabs/chalice#239]
I've tried adding various numpy configurations to the vendor directory to get numpy up and running (installing numpy in a virtualenv on an ec2 instance and downloading the resulting /usr/lib64/atlas-sse3/ and numpy directories, using the numpy and lib directories from this docker build https://github.com/ryansb/sklearn-build-lambda, and using this precompiled version https://github.com/Miserlou/lambda-packages/tree/master/lambda_packages) but I'm consistently getting this error message in cloudwatch:

```
Unable to import module 'app': Importing the multiarray numpy extension module failed. Most likely you are trying to import a failed build of numpy. If you're working with a numpy git repo, trygit clean -xdf(removes all files not under version control). Otherwise reinstall numpy.
```

**Comment by baileyspace** [comment]
In the vendor file I've been including the numpy directory as well as a lib directory that includes libatlas.so.3, libcblas.so.3, libclapack.so.3
libf77blas.so.3, libgfortran.so.3, liblapack.so.3, libptcblas.so.3, libptf77blas.so.3, and libquadmath.so.0. 

I decided to try making the endpoint return the directory structure of the lambda package as json. I can see that the numpy directory is included in the root directory but the lib directory isn't showing up.

When you add/remove files from the vendor directory, are those changes reflected after each deploy?

**Comment by baileyspace** [comment]
I needed to install the newest version of Chalice from github; the one at PyPI doesn't include the vendor updates.

**Comment by jamesls** [comment]
v0.6.0 has now been released that includes support for the `vendor/` directory.  Would you mind upgrading and seeing if you're still having issues?

**Comment by baileyspace** [comment]
This is working v0.6.0
