### ISSUE TITLE
Support for Lambda versions and versioning within API Gateway

### ISSUE THREAD

**Issue by davidvanleeuwen** [awslabs/chalice#24]
This is just an idea, so if you think this is not the place, please close this issue.

I've been thinking about a better versioning system for APIs on top of Lambda/API Gateway. It's nice you can create a stage variable and link that to an alias in Lambda. But Lambda also offers versioning, which is basically your API version... You would get something similar to https://zeit.co/now - where you deploy and get your URL back, but instead of just the stage, you could also get a version which lives forever and is hooked up to one of the aliases.

Although I have no clue yet on how to link that version to API gateway, it would be nice to think about it and see whether it is possible to get something like this done.

What do you think?

**Comment by jamesls** [comment]
I sketched out a similar idea to what you proposed over in #20.  Essentially, every "deploy" would create a new function version, and depending on the stage, we'd also update a lambda alias to point to that latest function version.

 If I understand what you're proposing, the biggest difference would be to also have some way to make those lambda function versions also accessible right?

Another way to get similar behavior would be to allow chalice to flip the alias to a different version.

I think this is something I'd like to support (in some form), but the specifics are still up for discussion.  Let's consolidate threads over at: https://github.com/awslabs/chalice/issues/20
