### ISSUE TITLE
Unable to install chalice==0.5.1 (0.5.0 works well)

### ISSUE THREAD

**Issue by vlcinsky** [awslabs/chalice#241]
I am unable to install the latest version (0.5.1) of chalice:

    $ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 16.04.2 LTS
    Release:        16.04
    Codename:       xenial

    $ python --version
    Python 2.7.12

The python is run from virtualenv.

Trying to install latest version of chalice fails:

    $ pip install chalice==0.5.1
    Collecting chalice==0.5.1
      Using cached chalice-0.5.1.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-VIqz1s/chalice/setup.py", line 43, in <module>
            'Programming Language :: Python :: 2.7',
          File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
            _setup_distribution = dist = klass(attrs)
          File "/home/javl/sandbox/playwith_chalice/.tox/py27/local/lib/python2.7/site-packages/setuptools/dist.py", line 320, in __init__
            _Distribution.__init__(self, attrs)
          File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
            self.finalize_options()
          File "/home/javl/sandbox/playwith_chalice/.tox/py27/local/lib/python2.7/site-packages/setuptools/dist.py", line 387, in finalize_options
            ep.load()(self, ep.name, value)
          File "/home/javl/sandbox/playwith_chalice/.tox/py27/local/lib/python2.7/site-packages/setuptools/dist.py", line 166, in check_specifier
            except packaging.specifiers.InvalidSpecifier as error:
        AttributeError: 'module' object has no attribute 'specifiers'
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-VIqz1s/chalice/

Installing version 0.5.0 works well:

    $ pip install chalice==0.5.0
    Collecting chalice==0.5.0
    Requirement already satisfied: typing==3.5.2.2 in ./.tox/py27/lib/python2.7/site-packages (from chalice==0.5.0)
    Requirement already satisfied: click==6.2 in ./.tox/py27/lib/python2.7/site-packages (from chalice==0.5.0)
    Requirement already satisfied: botocore<2.0.0,>=1.4.8 in ./.tox/py27/lib/python2.7/site-packages (from chalice==0.5.0)
    Requirement already satisfied: virtualenv<16.0.0,>=15.0.0 in ./.tox/py27/lib/python2.7/site-packages (from chalice==0.5.0)
    Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in ./.tox/py27/lib/python2.7/site-packages (from botocore<2.0.0,>=1.4.8->chalice==0.5.0)
    Requirement already satisfied: docutils>=0.10 in ./.tox/py27/lib/python2.7/site-packages (from botocore<2.0.0,>=1.4.8->chalice==0.5.0)
    Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in ./.tox/py27/lib/python2.7/site-packages (from botocore<2.0.0,>=1.4.8->chalice==0.5.0)
    Requirement already satisfied: six>=1.5 in ./.tox/py27/lib/python2.7/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.4.8->chalice==0.5.0)
    Installing collected packages: chalice
    Successfully installed chalice-0.5.0

**Comment by jamesls** [comment]
Interesting.  There was a change to the setup.py in 0.5.1 (https://github.com/awslabs/chalice/commit/61a534b72d835a4e5a8d5dd58c0025a7fcabb69e), but other than that I'm not sure what would be causing this.   Couple of questions:

* Can you try upgrading to 0.6.0?  Do you still have this issue?
* What's your `pip --version`?
* What's your setuptools version (`$ python -c "import setuptools; print setuptools.__version__"
23.1.0`)?

**Comment by noisefloor** [comment]
I have exactly the same problem, just I'm trying to upgrade from 0.5.1 to 0.6.
pip Version is 9.0.1, setuptools is 34.0.1(Python version is 2.7.12 on Ubuntu 16.4.2 - just in case it matters),

**Comment by vlcinsky** [comment]
@jamesls 
My environment is:
- Ubuntu 16.04.2 LTS
- Python 2.7.11
- using virtualenv created by tox==2.3.1 run by Python 3.5.2
- pip 9.0.1
- setuptools 34.3.0

Similarly as @noisefloor reported, trying to upgrade from 0.5.0 (@noisefloor reported from 0.5.1) it fails, this time somehow related to `click`:

    Exception:
    Traceback (most recent call last):
      File "/home/javl/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
        status = self.run(options, args)
      File "/home/javl/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
        prefix=options.prefix_path,
      File "/home/javl/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
        **kwargs
      File "/home/javl/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
        self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
      File "/home/javl/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
        isolated=self.isolated,
      File "/home/javl/.local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
        clobber(source, lib_dir, True)
      File "/home/javl/.local/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
        ensure_dir(destdir)
      File "/home/javl/.local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
        os.makedirs(path)
      File "/usr/lib/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 13] Operace zamítnuta: '/usr/local/lib/python2.7/dist-packages/click'

With clean install I manage to get chalice 0.6 installed without problems.

**Comment by jordal** [comment]
I have the same problem (not the click error, the original one in this issue) when trying a clean install of chalice-0.6.0 into a brand new virtual environment.

My environment:

- Python 2.7.12
- packaging-16.8
- pkg-resources-0.0.0
- pip-9.0.1
- setuptools-34.3.0

@vlcinsky did you do any special to get it working?

**Comment by vlcinsky** [comment]
@jordal as I use `tox` for automating creation of virtualenv, there are two methods which worked for me:

Ask tox to recreate the environment:

    $ tox -r

or manually removing the `.tox` environment and creating it again:

    $ rm -rf .tox
    $ tox

Tested it today and it still works. If you feel I closed the issue prematurely, reopen it.

**Comment by vlcinsky** [comment]
For your information, this is the `tox.ini` file I use for testing:

    [tox]
    envlist = py27
    skipsdist = True

    [testenv]
    commands = chalice --version
    deps = chalice
