### ISSUE TITLE
README.rst incorrect on positioning of --port option

### ISSUE THREAD

**Issue by jamesthiele** [awslabs/chalice#251]
`$ chalice --version`
`chalice 0.6.0`

This is what the README.rst file says:
`$ chalice --port=8080 local`
`Error: no such option: --port`

This is what it should say:
`$ chalice local --port=8080`
`Serving on localhost:8080`

**Comment by jamesls** [comment]
Fixed in https://github.com/awslabs/chalice/pull/260
