### ISSUE TITLE
Feature request: Option to indent/pretty print JSON response

### ISSUE THREAD

**Issue by colde** [awslabs/chalice#255]
It would be great to be able to set an option that would make the response data be pretty printed when returned. Either through an app wide setting, or for individual actions.

**Comment by stealthycoin** [comment]
That is the responsibility of the client. You can use something smarter than curl to pretty print JSON such as httpie which you can get from pip: `pip install httpie` and then you can use the `http` command:
```
➜ http $(chalice url)
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 74
Content-Type: application/json
.
.
.

{
    "hello": "world",
    "list": [
        1,
        {
            "nested": "content"
        },
        3
    ],
    "more": "value"
}
```

Its also colored in an actual terminal.
