### ISSUE TITLE
Option to manage lambda environment variables

### ISSUE THREAD

**Issue by arundhaj** [awslabs/chalice#257]
Currently, there is no option to create and manage lambda environment variables.

**Comment by emellis** [comment]
I have a PR up for this but it hasn't seen much traction. I'll rebase it again and see if I can't get things moving. https://github.com/awslabs/chalice/pull/243

**Comment by jamesls** [comment]
This is now implemented.  You can add an `environment_variables` to your config file, docs here: http://chalice.readthedocs.io/en/latest/topics/configfile.html?highlight=environment#stage-specific-configuration
