### ISSUE TITLE
Unsupported Media Type with custom media types and charset

### ISSUE THREAD

**Issue by sbuzonas** [awslabs/chalice#259]
In the [Tutorial: Request Content Types](https://github.com/awslabs/chalice#tutorial-request-content-types), it shows adding a form content type and posting with `httpie`, which uses `application/x-www-form-urlencoded; charset=utf-8`.

Using `chalice local`, an error is returned because of [app.py#L290](https://github.com/awslabs/chalice/blob/master/chalice/app.py#L290)

I'm using the following as a workaround, not sure if it's the best way to go about it:

```
if not [ct for ct in route_entry.content_types if content_type.startswith(ct)]:
```

**Comment by bradstimpson** [comment]
I seem to be experiencing the same issue; @sbuzonas can you provide a full code example with the work around?

**Comment by sbuzonas** [comment]
@bradstimpson I use that snippet on [app.py#L360](https://github.com/awslabs/chalice/blob/master/chalice/app.py#L360)

**Comment by stealthycoin** [comment]
This should no longer be a problem however the tutorial needs updating to work properly with `raw_body` in python 3. I will open a PR to fix that.
