### ISSUE TITLE
Passing a unicode type body to Response causes body to be json encoded

### ISSUE THREAD

**Issue by gene1wood** [awslabs/chalice#262]
https://github.com/awslabs/chalice/blob/a8d68083e8e76f096307cdd992686b658e39f1a2/chalice/app.py#L144-L145

If you pass a unicode typed body variable to the Response object it json encodes the value.

# Steps to reproduce

```
from chalice import Chalice, Response

app = Chalice(app_name='example')

@app.route('/')
def index():
    body = u'<h1>test</h1>'
    return Response(body=body,
                    status_code=200,
                    headers={'Content-Type': 'text/html'})
```

# Expected results

```
<h1>test</h1>
```

# Actual results

```
"<h1>test</h1>"
```

# Suggested change

It would make sense to check for `str` or `unicode` strings [here](https://github.com/awslabs/chalice/blob/a8d68083e8e76f096307cdd992686b658e39f1a2/chalice/app.py#L144-L145)

**Comment by stealthycoin** [comment]
Looks like this is still an issue. Although its worth noting that it is only an issue on python 2.
