### ISSUE TITLE
Best approach to working with extension modules in Chalice

### ISSUE THREAD

**Issue by gene1wood** [awslabs/chalice#265]
What is the best approach to working with [extension modules](https://docs.python.org/2/extending/extending.html) in Chalice?

For example, if my Chalice app uses the popular [`cryptography`](https://pypi.python.org/pypi/cryptography) module I encounter this problem

* I develop my Chalice app on my Ubuntu laptop
* I `chalice deploy` the app which causes extension modules to be built on my Ubuntu architecture system and added to my lambda zip
* I attempt to use my app in lambda and get errors like the following because my python extension modules weren't built on an Amazon Linux system

        Unable to import module 'app': libssl.so.1.0.0: cannot open shared object file: No such file or directory

I can spin up an Amazon Linux ec2 instance and install/build my `requirements.txt` modules, but what's the best way to then make Chalice aware of these modules, just copy them into `.chalice/venv`?

Once I do that, will my `chalice local` runs on my Ubuntu system no longer work because they're using extension modules build in Amazon Linux?

I'm mainly trying to determine if this is a problem that Chalice doesn't yet have a solution for or if I'm overlooking something and Chalice does support extension modules.

**Comment by gene1wood** [comment]
Maybe a workaround in the meantime would be to setup two directories, one for `local` and one for `deploy` put `app.py` in local and symlink to it in `deploy`. Then run `chalice local` in the `local` directory to build the extension modules on my local architecture and download the packages and libraries built on an amazon linux machine into the `deploy` directory's `.chalice` dir.

**Comment by stealthycoin** [comment]
The new tutorial for the beta version of Chalice actually specifically calls out the `cryptography` package. I haven't tried from an ubuntu laptop but I think building from that should work with the new build process. Open up a new issue if you run into any problems!
