### ISSUE TITLE
render_template

### ISSUE THREAD

**Issue by loudest** [awslabs/chalice#266]
Doesn't allow rendering of HTML templates on route

**Comment by stealthycoin** [comment]
What do you mean doesn't allow? Chalice is a microframework for building APIs. It doesn't have an opinion on how you do templates like Django does. You are free to use any of the template language libraries available in python. There are quite a few good ones so there is no reason for us to re-invent the wheel.

**Comment by jamesls** [comment]
Closing out issue.  There was recent bug where jinja2 wasn't importable, but this has been fixed https://github.com/awslabs/chalice/pull/421.  I'd suggest using `render_template` from jinja2 if you'd like to render html templates.  Let me know if you have any more questions.

**Comment by chmreid** [comment]
For those stumbling on this issue looking for a way to use `jinja2.render_template()` with a Chalice app, see [this Medium post](https://medium.com/richcontext-engineering/creating-a-serverless-blog-with-chalice-bdc39b835f75) for a nice example.
