### ISSUE TITLE
Chalice rollback

### ISSUE THREAD

**Issue by ashimaathri** [awslabs/chalice#269]
Hi,

Is there a way to rollback a deploy in chalice or to specify the API gateway deployment to be used when doing `chalice deploy`? 

Thanks!

**Comment by deakolt** [comment]
`chalice deploy dev`, `chalice deploy prod`, etc will specify the API gateway that is deployed.

**Comment by stealthycoin** [comment]
The `chalice deploy <stage-name>` form of the deploy command is acutally deprecated now:

```
➜ chalice deploy foo
You've specified a deploy command of the form 'chalice deploy <stage>'
This form is deprecated and will be removed in a future version of chalice.
You can use the --api-gateway-stage to achieve the same functionality, or the newer '--stage' argument if you want an entirely set of separate resources.
```
@ashimaathri There is no provided way of rolling back a deployment. Though there are many ways of achieving something similar. As @deakolt suggested you can use as separate stage for `dev` and `prod` using the `--stage` command will maintain two separate sets of AWS resources so there will be no overlap between them and nothing you do on `dev` will affect `prod`. Once you are happy with tests passing on the dev stage you can make a tag in whatever version control you are using and deploy it to prod, and begin testing changes in dev again. If you want to rollback all you would do is checkout the tag of the last known working version and deploy that to prod.

**Comment by ashimaathri** [comment]
Thanks! For now we just revert and roll forward.
