### ISSUE TITLE
Add the ability to specify a profile on the CLI

### ISSUE THREAD

**Issue by sesh** [awslabs/chalice#28]
Some (most?) of us have access to multiple AWS accounts from the command line. It would be super-handy to be able to specify which profile to use with the `--profile` CLI argument like you can with `awscli`.

**Comment by Depado** [comment]
A workaround while waiting for this feature :

Store your credentials in your project (and don't version it of course) and change the `AWS_CONFIG_FILE` environment variable to point to that file before executing chalice. I didn't test it yet but that should do the trick.

**Comment by garnaat** [comment]
You should be able to just set ``AWS_PROFILE`` environment variable to pick the desired profile from your standard config file.  But I agree having a ``--profile`` option makes sense.

**Comment by MartijnHarmenzon** [comment]
I noticed this is possible on deployments also, which is great. But can it also be done on local like:
`chalice local --profile my-profile-name`?
