### ISSUE TITLE
Custom Authorization Removed in 0.7.0

### ISSUE THREAD

**Issue by nedlowe** [awslabs/chalice#285]
Hi,

I see that authorization_type and authorizer_id have been removed, and a new example using Cognito User Pools added instead... But what about if we are using a custom lambda for authorisation?

I just upgraded Chalice and see the change (chalice deploy fails), and I don't seem to be able to see the replacement approach for custom lambdas?

Thanks,
Ned

**Comment by liupingyi** [comment]
+1...

**Comment by jamesls** [comment]
Hi, I'm adding this back, tracking here: https://github.com/awslabs/chalice/pull/322

**Comment by jamesls** [comment]
Fixed via https://github.com/awslabs/chalice/pull/322.
