### ISSUE TITLE
Adding `api_key_required` to the route decorator causing an error

### ISSUE THREAD

**Issue by artkay** [awslabs/chalice#290]
I recently updated my API from Chalice 0.6 to Chalice 0.7 and I have an issue deploying it when I add `api_key_required=True` to the route decorator:

```python

@app.route('/{id}', api_key_required=True)
def index(id):
   # ...
```

When I try to deploy the API I am getting this error:

> An error occurred (BadRequestException) when calling the PutRestApi operation: Invalid Swagger 2.0 input.

If I remove the `api_key_required=True` part - it works well.

**Comment by jamesls** [comment]
This has been fixed via https://github.com/awslabs/chalice/pull/282

**Comment by artkay** [comment]
@jamesls got it, thanks!

**Comment by artkay** [comment]
@jamesls I would like to ask if there is a minor release in the plans? The one that will include the fix.

**Comment by jamesls** [comment]
0.8.0 now has this fix (along with python3 support!)
