### ISSUE TITLE
sourceIp not informed on Local deployment

### ISSUE THREAD

**Issue by angelbarrera92** [awslabs/chalice#293]
Hi!

I found an _'issue'_. I am trying to persists some context data in database _(audit),_ one of the main fields is `sourceIp` what is inside `context.identity. `

The problem is when identity is not inside context on local development. I can mock then on testing time but during local development/debugging is quite difficult. 

Is it an issue? or have i to get the origin ip from `headers.host`?

Thanks in advance!

**Comment by jamesls** [comment]
I think this is just missing functionality in `chalice local`.  Should be easy to add, in local mode I think we'd just set the sourceIp to be 127.0.0.1.

Marking as a feature request.

**Comment by angelbarrera92** [comment]
PR at #341

**Comment by stealthycoin** [comment]
Closing this since the PR was accepted.
