### ISSUE TITLE
Packaging issue with Python3

### ISSUE THREAD

**Issue by nedlowe** [awslabs/chalice#298]
This can be easily worked around, but thought I would report it anyway.

When upgrading a package to Python3, a new set of folders are created in /.chalice/venv - and the packager somehow gets confused when pulling in packages.

Let's say requirements.txt wants v1.0.1 of a package and in python3 that is satisfied, but in python2 only v1.0.0 is available, the packager can pull in the 1.0.0 version into the zip from the python2 folder.

I worked around by deleting the python2 folders in /.chalice/venv and redeploying.

Thanks.

**Comment by jamesls** [comment]
Hi, thanks for reporting.  Do you have steps to repro the issue?  I tried a few combinations of switching between py2 and py3 with package updates but wasn't able to get it to fail.  Was there a specific package/version range I could try this with that demonstrates the issue?

**Comment by nedlowe** [comment]
These are the steps I took (if you can't reproduce I can try):

1. Create a Python 2.7 virtualenv/project in Chalice
2. pip install package
3. Write code etc
4. chalice deploy
5. Create a Python 3.6 virtualenv
6. Deploy existing project to Chalice - "do you want to update to Python 3" - yes.
7. pip install --upgrade package in the 3.6 virtualenv for whatever reason
8. chalice deploy in the 3.6 virtualenv
9. Deployed package contains the older version from the previous deployment

I'm pretty sure it's due to the previous deployment, because as mentioned when I deleted the Python 2 folders from /.chalice/venv and redeployed it worked fine.  Note that this happened on all ~10 of my Chalice services, so it wasn't a one off.

Thanks!

**Comment by stealthycoin** [comment]
@nedlowe Thanks for reporting this. The packager has been completely reworked and this should no longer be an issue. Give it a try and open a new issue if you run into any issues!
