### ISSUE TITLE
Add support for non JSON payloads

### ISSUE THREAD

**Issue by yieldthought** [awslabs/chalice#30]
Chalice is a really cool microframework! All the examples focus on returning JSON responses. Is it possible to serve HTML pages? Or to specify different response headers, e.g. 301 redirect and so on? Or is all of this out of scope and chalice is really just for writing REST JSON APIs?

**Comment by jamesls** [comment]
It is currently not possible to do that.  I think initially I'd like to focus on rest JSON APIs (which is all it supports for now), but I would like to add support for other content types.

**Comment by discobean** [comment]
I'm really enjoying using chalice, but it is limited that I cannot return text/plain, text/xml or binary types for a specific project we are working on.  So +1 for this for sure.

**Comment by khornberg** [comment]
@discobean This is possible with manual tweaks. 
See the `Method Response` part of the article
https://kennbrodhagen.net/2016/01/31/how-to-return-html-from-aws-api-gateway-lambda/

As far as I know and in my playing around with it, API Gateway fails to provide binary support. I believe it makes everything UTF-8.

**Comment by martyni** [comment]
that article makes it sound a lot more complicated than it needs to be.
1- deploy your app using chalice deploy
2- navigate to your api gateway and click on the HTTP method (default is GET) you want returned in a format other than json
3- edit its Method Response Content-Type from application/json to your chosen format|
4- make sure to select Actions -> deploy API (just click through pressing buttons like deploy and save changes)
Would also like to see this built into the route decorator as something like a content-type kwarg

**Comment by khornberg** [comment]
I agree. Manually doing it was tedious. The `Serverless` framework allows for it quite easily and has it in their docs on how to do it.

**Comment by errordeveloper** [comment]
> ...think initially I'd like to focus on rest JSON APIs.

Makes so much sense, however, amongst the HTML example, @yieldthought suggested the following:

> Or to specify different response headers, e.g. 301 redirect and so on?

This would be great for my use-case, namely I'd like to redirect to a location within the same app.
301s and custom headers are widely used in JSON APIs, even pretty simple APIs utilise these things.

I agree other content types may be too much to ask right now, but please consider the above :)

**Comment by jamesls** [comment]
You can now specify redirects using the custom `chalice.Response` class added in v0.6.0:

```python
@app.route('/redirect', content_types=['text/plain'])
def hello_world():
    url = app.current_request.raw_body.strip()
    return Response(
        status_code=301,
        body='',
        headers={'Location': url})
```

More info here: http://chalice.readthedocs.io/en/latest/quickstart.html#tutorial-customizing-the-http-response

The only caveat to be aware of is that binary content still isn't supported.  API Gateway requires some additional work to configure which content types are binary (https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings.html).  I do have this on my backlog though.

Let me know if you have any questions/feedback about this feature.

**Comment by dmulter** [comment]
FYI, I'm looking for support to receive content-type `application/xml` payloads. I don't need any special parsing or handling other than permitting access to the request body via `app.current_request.raw_body`.

**Comment by danielcarcich** [comment]
FYI, the customizing-the-http-response documentation is now here: https://aws.github.io/chalice/tutorials/basicrestapi.html#customizing-the-http-response
