### ISSUE TITLE
Add support python 3.6

### ISSUE THREAD

**Issue by andriisoldatenko** [awslabs/chalice#301]
More info https://aws.amazon.com/about-aws/whats-new/2017/04/aws-lambda-supports-python-3-6/

I can add support to chalice.
What do you think?

**Comment by andriisoldatenko** [comment]
https://github.com/awslabs/chalice/pull/214 my old PR

**Comment by ehammond** [comment]
I followed the chalice docs to create a Python 3.6 AWS Lambda function and it worked smoothly.

What else is needed?

**Comment by kadrach** [comment]
https://github.com/awslabs/chalice/pull/296 happened the day support for 3.6 was announced.
