### ISSUE TITLE
Chalice stages and API Gateway stages

### ISSUE THREAD

**Issue by nedlowe** [awslabs/chalice#302]
Hi,

I understand why Chalice stages were broken out and think it makes sense.

However, I think it ought to still use the 'old' API Gateway approach to stages (a single URL with different /$stage appended) - or it should at least be an option...

Am I missing something?

Many thanks,
Ned

**Comment by jamesls** [comment]
There's a new config option that lets you control the API gateway stage name, `api_gateway_stage`.

However, if I'm understanding correctly, it sounds like you want to be able to deploy to multiple API Gateway stages within a single rest API, is that correct?

**Comment by nedlowe** [comment]
Thanks for the response.

So basically I am getting a bit bogged down with the number of different bits of infrastructure I need to manage, and API Gateway seems like a relatively easy place I can reduce things.

I was thinking that it would be cool to:
- Have a single REST API
- Multiple stages within that API
- Control lambda execution using something like https://aws.amazon.com/blogs/compute/using-api-gateway-stage-variables-to-manage-lambda-functions/

As an aside, it would also be cool if we could control authorisation by stage - my prod environment uses Cognito, but we were thinking it would easier to use x-api-key/custom auth for dev environments to save time authenticating against Cognito.  But I'm not sure how we would do that within a single API Gateway interface even if Cognito allowed us to specify, so that would presumably have to be multiple APIs...

**Comment by nedlowe** [comment]
Hmm - I just tried setting rest_api_id manually in deployed.json and config.json, and it seems to work...

**Comment by deakolt** [comment]
That same workaround worked for me.

Two solutions that I think are viable:

1) The ability to deploy to different stages of the same API Gateway API, or
2) Append the stage name to the API Gateway name (as already happens with the lambda functions).

As it stands, the API Gateways are somewhat confusing since they all have the same name.

**Comment by colde** [comment]
I would add that it seems really counter intuitive first time, that selecting a new stage with Chalice deploys to a new API  with the "dev" stage, instead of to the existing API with the new stage name. It seems to work counter to how API Gateway was designed.

**Comment by stealthycoin** [comment]
The default name is changing to v1 in the https://github.com/awslabs/chalice/pull/431 hopefully this will clear up some of the confusion about how this is intended to be used. If this doesn't address the issue you can open another issue and make a specific feature request.
