### ISSUE TITLE
Updating a route's URL doesn't delete old resource

### ISSUE THREAD

**Issue by budowski** [awslabs/chalice#305]
When I update a route's URL, the old resource (for the old URL) is not deleted.

This might be a hard-to-solve issue - maybe save a local cache of function/URL mapping, and when the URL changes (assuming function name stays the same), `chalice deploy` will delete the old resources.

**Comment by jamesls** [comment]
I think I see the issue.  The internals recently changed to first generate a swagger API and then import/update the api gateway API (as opposed to making individual API calls for each route).

The default setting is `merge` for `put_rest_api`, but it needs to be `overwrite`.  Should be a quick fix  Thanks for reporting.
