### ISSUE TITLE
"Content-type: application/json; charset=utf-8" causes a 415 Unsupported Media Type

### ISSUE THREAD

**Issue by budowski** [awslabs/chalice#306]
Basically the default supported content_type should also support the `charset=utf-8` option (it currently doesn't, so if a client sends a `Content-type: application/json; charset=utf-8` header, the API responds with a `415 Unsupported Media Type`). This is important IMHO, since some clients (like Android's [OkHttp](https://github.com/square/okhttp/) add the `charset=utf-8` by default).

So currently the workaround is this:
```python
@app.route('/myRoute', methods=['POST'], content_types=['application/json; charset=utf-8', 'application/json'])
def myRoute():
      pass
```

**Comment by jamesls** [comment]
Thanks for reporting.  Confirmed bug.

**Comment by jamesls** [comment]
Fixed via https://github.com/awslabs/chalice/pull/312
