### ISSUE TITLE
Export CHALICE_DEV_URL=<url-endpoint> ?

### ISSUE THREAD

**Issue by e12e** [awslabs/chalice#32]
From the readme:

> Additionally, the API Gateway endpoints will be shortened to https://endpoint/dev/ for brevity. Be sure to substitute https://endpoint/dev/ for the actual endpoint that the chalice CLI displays when you deploy your API (it will look something like https://abcdefg.execute-api.us-west-2.amazonaws.com/dev/.

Why not let the `chalice`  command-line export/set the URL as an environment variable? It should make scripting a lot easier (right now it would probably be possible to `|tail -1 |read URL` - but being able to check the exit-code of `chalice`, and then know that that one can go on with testing  `http ${CHALICE_DEV_URL}` or equivalent might make things even easier?

**Comment by e12e** [comment]
Giving this a bit more consideration, perhaps it would be even better to write the url to a file, like `.endpoint.dev` - or both. Might make it easier to keep abstractions working well cross-platform (perhaps with a sub-command: `calice url` that simply output the current url end-point?

**Comment by jamesls** [comment]
I think this would be helpful.  I think I'll need to rework the `.chalice` structure internals.  I think in general I would like to have some file that tracks all the resources we create for you (in addition to the rest api id and stage so we can return the url to you).  That will also help facilitate other commands such as `chalice delete` (#40) and `chalice resources` (#11), which I'd like to add.

**Comment by jamesls** [comment]
This has been resolved in https://github.com/awslabs/chalice/pull/169, which adds a `chalice url` command that prints the deployed URL to stdout.
