### ISSUE TITLE
Having issue with one test

### ISSUE THREAD

**Issue by angelbarrera92** [awslabs/chalice#326]
Hi again!

I was developing this feature # 293 on my fork when I detected that a test was failing:

tests/functional/cli/test_cli.py:143:test_can_package_with_single_file

I move to your master branch and it continues appearing. I followed the CONTRIBUTING.rst file and the error does not disappear. It's something wrong on my local environment?

Thanks in advance!

**Comment by jamesls** [comment]
What's the error message?

**Comment by angelbarrera92** [comment]
I attached the output here:
[failed_test.txt](https://github.com/awslabs/chalice/files/978246/failed_test.txt)

Thanks!

**Comment by jamesls** [comment]
Ah I'll fix that.  Looks like the test is relying on the order of the file list.
