### ISSUE TITLE
Error on chalice deploy: "The write operation timed out"

### ISSUE THREAD

**Issue by ehammond** [awslabs/chalice#330]
chalice (0.8.0?) had been working for me a week ago, but when I tried again with a fresh install (0.8.1) today, I'm now getting timeouts on deploy.

    $ virtualenv --python $(which python3.6) $HOME/.virtualenvs/chalice-python3.6
    $ source $HOME/.virtualenvs/chalice-python3.6/bin/activate
    $ pip install chalice
    $ python --version
    Python 3.6.1
    $ chalice --version
    chalice 0.8.1

    $ chalice new-project helloworld
    $ cd helloworld
    $ time chalice deploy
    Initial creation of lambda function.
    Updating IAM policy.
    Creating deployment package.
    ('Connection aborted.', timeout('The write operation timed out',))
    
    real	5m55.284s
    user	0m3.388s
    sys	0m0.384s

It spends over five minutes uploading something at a fairly solid 0.5Mbps. How much data needs to be uploaded for a bare deploy?

Is it possible the upload is failing for some reason and retrying over and over? Is there a way to get more verbose debug messages?

I tried this with two distinct Internet connection paths to help reduce that as a suspect.

I'm using Ubuntu 17.04 Zesty.

**Comment by jamesls** [comment]
I tried a few different options, but I'm not seeing any timeouts:

```
$ mktmpenv --python $(which python3.6)
Running virtualenv with interpreter /usr/local/bin/python3.6
...
(tmp-db699489363cc6a7) $ pip install chalice
(tmp-db699489363cc6a7) $ python --version
Python 3.6.1
(tmp-db699489363cc6a7) $ chalice --version
chalice 0.8.1
(tmp-db699489363cc6a7) $ chalice new-project helloworld081
(tmp-db699489363cc6a7) $ cd helloworld081/
(tmp-db699489363cc6a7) $ time chalice deploy
Initial creation of lambda function.
Creating role
Creating deployment package.
Initiating first time deployment...
Deploying to: dev
https://9q3tdyldk7.execute-api.us-west-2.amazonaws.com/dev/

real	0m22.901s
user	0m2.596s
sys	0m0.641s
```

Could you share the output of `chalice --debug deploy`?  That should give us a better idea of what's going wrong

**Comment by ehammond** [comment]
Thanks for investigating. Some hours later on a third Internet connection, it started working, and it only took a short time at around the same 0.5 Mbps. There was no change to the code, so it may have been the network or something on the AWS side that was causing the problem.

I will keep the --debug option in mind if this happens again in the future.

If you happen to notice somewhere in the code that might cause specific situations to spin sending data for 5 minutes, consider adding some extra error information beyond what it showed above.
