### ISSUE TITLE
Chalice does not automatically pick right version of Python to use

### ISSUE THREAD

**Issue by shaftoe** [awslabs/chalice#333]
Hi, I'm trying to upgrade a Chalice project to latest Python runtime version following steps from http://chalice.readthedocs.io/en/latest/topics/pyversion.html , but apparently the right version of Python doesn't get automatically picked as supposed to. This is how I can reproduce it:

    ✔ /tmp/testing-chalice
    10:56 $ virtualenv --python python3 venv3
    Running virtualenv with interpreter /usr/local/bin/python3
    Using base prefix '/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6'
    New python executable in /private/tmp/testing-chalice/venv3/bin/python3.6
    Also creating executable in /private/tmp/testing-chalice/venv3/bin/python
    Installing setuptools, pip, wheel...done.
    ✔ /tmp/testing-chalice
    10:56 $ source venv3/bin/activate
    (venv3) ✔ /tmp/testing-chalice
    10:57 $ chalice --version
    chalice 0.8.2
    (venv3) ✔ /tmp/testing-chalice
    10:57 $ python --version
    Python 3.6.0
    (venv3) ✔ /tmp/testing-chalice
    10:57 $ chalice new-project test-versions
    (venv3) ✔ /tmp/testing-chalice
    10:57 $ cd test-versions
    (venv3) ✔ /tmp/testing-chalice/test-versions
    10:57 $ chalice package test-package
    Creating deployment package.
    (venv3) ✔ /tmp/testing-chalice/test-versions
    10:57 $ grep -C 3 python test-package/sam.json
        "Properties": {
            "Handler": "app.app",
            "CodeUri": "./deployment.zip",
            "Runtime": "python2.7",
            "Events": {
            "indexget6a99": {
                "Type": "Api",

Running on up to date MacBook Air, installed Python v3 via Brew

**Comment by stealthycoin** [comment]
Hmm I can't replicate this:

```
➜ virtualenv --python ~/.pyenv/versions/3.6.0/bin/python3 shaftoe
.
.
.
➜ source shaftoe/bin/activate
(shaftoe) ➜ python --version
Python 3.6.0
(shaftoe) ➜ pip install chalice
.
.
.
(shaftoe) ➜ chalice --version
chalice 0.8.2
(shaftoe) ➜  chalice new-project test-versions
(shaftoe) ➜  cd test-versions
(shaftoe) ➜  chalice package test-package
Creating deployment package.
(shaftoe) ➜  grep -C 3 python test-package/sam.json
    "APIHandler": {
      "Type": "AWS::Serverless::Function",
      "Properties": {
        "Runtime": "python3.6",
        "Handler": "app.app",
        "CodeUri": "./deployment.zip",
        "Events": {
```

Chalice uses `sys.verison_info[0]` to determine the major python version of your environment. Can you try this in your virtualenv:
```
(shaftoe) ➜ python
Python 3.6.0 ...
>>> import sys
>>> sys.version_info[0]
3
>>>
```
We simply take this value and map it to the nearest version of python that lambda supports:
https://github.com/awslabs/chalice/blob/master/chalice/config.py#L137-L142
https://github.com/awslabs/chalice/blob/master/chalice/package.py#L101

I have also never used python 3 installed from brew so I don't know if that could be contributing to the issue.

**Comment by shaftoe** [comment]
Thanks for help.
That's odd, I can see the expected version from version_info:
```
(venv3) ✔ /tmp/testing-chalice
10:11 $ python
Python 3.6.1 (default, Apr  4 2017, 09:40:21)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.version_info[0]
3
```

I guess for some reason when running `chalice` the wrong version of the interpreter is executed, even if inside the virtualenv, will try to dig deeper as soon as I find some time

**Comment by stealthycoin** [comment]
I would suggest setting a breakpoint [here](https://github.com/awslabs/chalice/blob/master/chalice/config.py#L141) and see what that returns to start with.

**Comment by jamesls** [comment]
I noticed in your original output you're not installing chalice in your venv:

```
✔ /tmp/testing-chalice
10:56 $ virtualenv --python python3 venv3
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6'
New python executable in /private/tmp/testing-chalice/venv3/bin/python3.6
Also creating executable in /private/tmp/testing-chalice/venv3/bin/python
Installing setuptools, pip, wheel...done.
✔ /tmp/testing-chalice
10:56 $ source venv3/bin/activate
(venv3) ✔ /tmp/testing-chalice
10:57 $ chalice --version
chalice 0.8.2
```

What could be happening is chalice is installed globally under python2, which would explain why it's not using the python3 version.  Could you try `pip install chalice` in your virtualenv?  You can also double check this by running `which chalice` and it should point to a location under the `/private/tmp/testing-chalice/venv3/bin` location.

**Comment by shaftoe** [comment]
Right on! great catch @jamesls , thanks for the help

**Comment by gmetzker** [comment]
Thanks this helped me as well.  In my case I have pip pointing to pip3, I was also running in a python3.6 virtual environment but for some reason Chalice was installed globally under python2.

Would be nice maybe to have the python runtime version available as a variable in the chalice config file so we can be more explicit.
