### ISSUE TITLE
using boto3 lambda invoke() to run Chalice lambda

### ISSUE THREAD

**Issue by Jim-Knoll** [awslabs/chalice#335]
There are times I would like to call the lambda function directly from python boto3 running on an ec2.  Is this supported?   Are there code examples?   I keep running into problem with 'Did you forget to set the Content-Type'  

But when I use the API GW (via curl from the same box I run the python from) I have no problems.   I would like to avoid the API GW for the local Python use case.

I also get the same error if I try and call the lambda direct from the CLI

**Comment by stealthycoin** [comment]
What would be the use case for this? I don't see why you would need to do this. To avoid API gateway? 

You would need to provide an event to the lambda function in the same format as API gateway does.
Here is the function that lambda calls in chalice when an event is received, and a list of the keys we assume are present on the event.
https://github.com/awslabs/chalice/blob/master/chalice/app.py#L413-L419

You could also look at the example provided by apigateway for testing lamba functions:
```javascript
{
  "body": "{\"test\":\"body\"}",
  "resource": "/{proxy+}",
  "requestContext": {
    "resourceId": "123456",
    "apiId": "1234567890",
    "resourcePath": "/{proxy+}",
    "httpMethod": "POST",
    "requestId": "c6af9ac6-7b61-11e6-9a41-93e8deadbeef",
    "accountId": "123456789012",
    "identity": {
      "apiKey": null,
      "userArn": null,
      "cognitoAuthenticationType": null,
      "caller": null,
      "userAgent": "Custom User Agent String",
      "user": null,
      "cognitoIdentityPoolId": null,
      "cognitoIdentityId": null,
      "cognitoAuthenticationProvider": null,
      "sourceIp": "127.0.0.1",
      "accountId": null
    },
    "stage": "prod"
  },
  "queryStringParameters": {
    "foo": "bar"
  },
  "headers": {
    "Via": "1.1 08f323deadbeefa7af34d5feb414ce27.cloudfront.net (CloudFront)",
    "Accept-Language": "en-US,en;q=0.8",
    "CloudFront-Is-Desktop-Viewer": "true",
    "CloudFront-Is-SmartTV-Viewer": "false",
    "CloudFront-Is-Mobile-Viewer": "false",
    "X-Forwarded-For": "127.0.0.1, 127.0.0.2",
    "CloudFront-Viewer-Country": "US",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Upgrade-Insecure-Requests": "1",
    "X-Forwarded-Port": "443",
    "Host": "1234567890.execute-api.us-east-1.amazonaws.com",
    "X-Forwarded-Proto": "https",
    "X-Amz-Cf-Id": "cDehVQoZnx43VYQb9j2-nvCh-9z396Uhbp027Y2JvkCPNLmGJHqlaA==",
    "CloudFront-Is-Tablet-Viewer": "false",
    "Cache-Control": "max-age=0",
    "User-Agent": "Custom User Agent String",
    "CloudFront-Forwarded-Proto": "https",
    "Accept-Encoding": "gzip, deflate, sdch"
  },
  "pathParameters": {
    "proxy": "path/to/resource"
  },
  "httpMethod": "POST",
  "stageVariables": {
    "baz": "qux"
  },
  "path": "/path/to/resource"
}
```

I think it would be far easier to simply use `curl` or if you are in python and have `boto3` you already have access to `requests` so a simple `requests.get`.

**Comment by mheffner** [comment]
@stealthycoin Any suggestions for a use case where the initial API GW request has a strict time limit, so ideally the initial call would internally invoke a given Lambda function async? The example would be:

1. Call API GW Lambda
2. API GW lambda generates unique work ID, saves meta data in DDB
3. Invoke an async lambda call, passing work ID (use boto3 call semantics)
4. API GW lambda returns success to user (in under 3 secs), returns work ID
5. Async lambda runs to completion (20-30secs), saves state in DDB
6. Original caller polls status of work ID until status is complete

It would be nice to be able to define the async lambda within the same chalice project, but it seems like any function must be defined as an API GW route?

**Comment by mheffner** [comment]
> Any suggestions for a use case where the initial API GW request...

Oops, never mind I found the docs for: https://github.com/aws/chalice/blob/master/docs/source/topics/purelambda.rst
