### ISSUE TITLE
Another issue in a test (comparing list)

### ISSUE THREAD

**Issue by angelbarrera92** [awslabs/chalice#337]
Hi again!

I was developing this feature #293 on my fork when I detected that a test was failing:

tests/functional/test_utils.py:test_can_zip_recursive_contents

I can fix the error. Simply sort the list before compare. I will do a pull request.

[TestFailure.txt](https://github.com/awslabs/chalice/files/999217/TestFailure.txt)

Thanks in advance!

**Comment by jamesls** [comment]
Thanks for letting us know, I've merged #338.
