### ISSUE TITLE
Manually provided role not updated on redeployment

### ISSUE THREAD

**Issue by mmcdermo** [awslabs/chalice#339]
It would be handy if chalice updated the IAM role for the lambda function whenever it performs an update on the function. To demonstrate that it doesn't currently have this functionality:

If you configure chalice to use a manually provided role in config.json with:

```
"manage_iam_role":false
"iam_role_arn":"arn:aws:iam::<account-id>:role/<role-name>"
```

Then 

```
chalice deploy
```

Then change the role to something else:
```
"iam_role_arn":"arn:aws:iam::<account-id>:role/<role-2-name>
```

Then deploy again:
```
chalice deploy
```

You'll see that the deployed lambda function still retains the first role. This makes sense, as only environment variables are updated inside awsclient.TypedAWSClient.update_function.

**Comment by kyleknap** [comment]
Closing issue out. It got fixed in this PR: https://github.com/awslabs/chalice/pull/363. It will be available in the next chalice release.
