### ISSUE TITLE
Use exceptions to return error responses

### ISSUE THREAD

**Issue by JamieCressey** [awslabs/chalice#34]
I've not delved too deep into this yet, so I'm not sure how straight forward this would be to implement...

Having the ability to use exceptions to return an error response (and correct HTTP response code) would be extremely useful. A pseudo example:

Exception class:
```
class UnauthorizedException(ChaliceError):
    STATUS_CODE = 401
```

App logic:
```
if not authenticate(user):
    raise UnauthorizedException('You are not authenticated')
```

Response example (inc. correct response headers):
```
{"error": e.message}
```

Having quickly checked the source code, it looks like it should just be a cause of creating the exceptions and adding them to the `ALL_ERRORS` list. 

Thoughts?

**Comment by jamesls** [comment]
I think that's a great idea.

**Comment by jamesls** [comment]
Closing, implemented in https://github.com/awslabs/chalice/pull/37
