### ISSUE TITLE
Method Request with Authorization = 'AWS_IAM' 

### ISSUE THREAD

**Issue by 3dw1np** [awslabs/chalice#343]
In chalice 0.6.0, I was able to setup the Authorization = 'AWS_IAM' by adding this **authorization_type='AWS_IAM'** in ``@app.route(...)`` calls.

Now since the version 0.8.1, we use **authorizer=authorizer** in ``@app.route(...)`` calls and provide a CognitoUserPoolAuthorizer  or CustomAuthorizer object.

How I can simply define a AWS_IAM Authorization Type for using AWS IAM permissions ?

**Comment by 3dw1np** [comment]
Seems there is already a PR [here](https://github.com/awslabs/chalice/pull/334)

**Comment by jamesls** [comment]
https://github.com/awslabs/chalice/pull/334 has been merged, closing issue.
