### ISSUE TITLE
autogen_policy from config.json is ignored when doing a chalice package

### ISSUE THREAD

**Issue by uzd** [awslabs/chalice#354]
When we do a "chalice package", we noticed that the autogen_policy was defaulting to true, completely ignoring the '"autogen_policy": false' in the config.json. After debugging, we found that the "create_config_obj" function (called in the 'package' cli command) defaulting autogen_policy to true.

**Comment by jamesls** [comment]
Thanks for reporting, marking as a bug.

**Comment by uzd** [comment]
FYI we've found a workaround by using autogen_policy in combination with iam_policy_file.
