### ISSUE TITLE
Connecting to an RDS from Chalice?

### ISSUE THREAD

**Issue by watdeo** [awslabs/chalice#378]
I'm new to chalice and aws in general. What's the best practice when it comes to connecting to Amazon's RDS? I have already set up a postgres RDS through the web panel, so I want my chalice app to be able to retrieve and store data after a GET or POST request from the user.

Here is what I have:

```
from chalice import Chalice
import psycopg2

app = Chalice(app_name='test')
db_user = 'test'
db_pass = 'password'
db_host = 'https://.....'
db_port = 5432

@app.route('/save_data', methods=["POST"])
def save_data():
    with psycopg2.connect(user=db_user, password=db_pass, ...) as conn:
        with conn.cursor() as cur:
            cur.execute("INSERT INTO test (num, data) VALUES (%s, %s)", (1,2))

@app.route('/get_data')
def get_data():
    with psycopg2.connect(user=db_user, password=db_pass, ...) as conn:
        with conn.cursor() as cur:    
            cur.execute("SELECT * FROM test")


@app.route('/something')
def something():
    with psycopg2.connect(user=db_user, password=db_pass, ...) as conn:
        with conn.cursor() as cur:    
            cur.execute(....)  # some other query
```

Is this a valid way of connecting to my RDS instance? Is there an easier way to build/teardown the db connection after a request? Is this safe from concurrency issues across many concurrent requests?

Or, if I'm completely off, what's the proper way to connect to the RDS from Chalice routes?

**Comment by stealthycoin** [comment]
It should be safe to make the connection at the module level and reuse it in all of your routes because any one instance of your lambda function will only every be handling one request at a time, so there will be no contention for your connection object.

 This will speed things up since it won't be creating a new connection for each request, only on fresh cold-starts of the lambda container, which will only happen when concurrent requests come in and need additional containers spun up to handle them.

**Comment by jamesls** [comment]
Let us know if you have any more questions.

**Comment by aneesha** [comment]
Is this still the recommended way to connect to a database?

**Comment by ilhamfadllah** [comment]
@aneesha Hi, newbie here to use Chalice. Not sure this recommended way. Just share how i connect to Aurora serverless w/ Data API enabled

```
import boto3

rdsClient = boto3.client('rds-data')

dbName = ''
dbArn = ''
dbCredentialsSecretStoreArn = ''

def execute_sql_statement(sql):
    response = rdsClient.execute_statement(
        secretArn=dbCredentialsSecretStoreArn,
        database=dbName,
        resourceArn=dbArn,
        sql=sql
    )
    return response
   ```
