### ISSUE TITLE
Browser-provided Accept header not accepted

### ISSUE THREAD

**Issue by twslankard** [awslabs/chalice#391]
Hi all,

I have a Chalice-based app that sends an HTML form that allows the user to download a file upon submission. The response content-type is `application/octet-stream`.

The browser (Firefox) sends the Accept header `text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`, which contains the wildcard `*/*`. However, the response from the Chalice app is a JSON response:

    {
        "Message": "Request did not specify an Accept header with application/octet-stream, The response has a Content-Type of application/octet-stream. If a response has a binary Content-Type then the request must specify an Accept header that matches.",
        "Code": "BadRequest"
    }

I've also tried the request in Postman, setting the Accept header to the wildcard `*/*` explicitly, and I receive the same error. Only when I set the Accept header `application/octet-stream` does the request succeed.

I would expect the wildcard accept header (and the browser's default) to allow the request to succeed.

Thanks!

**Comment by jamesls** [comment]
I've run into this as well, but I'm not sure if we have any options in chalice to make this work.  This is the behavior of API gateway.  From: http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings-workflow.html

> When a request contains multiple media types in its Accept header, API Gateway only honors the first Accept media type. In the situation where you cannot control the order of the Accept media types and the media type of your binary content is not the first in the list, you can add the first Accept media type in the binaryMediaTypes list of your API, API Gateway will return your content as binary. For example, to send a JPEG file using an <img> element in a browser, the browser might send Accept:image/webp,image/*,*/*;q=0.8 in a request. By adding image/webp to the binaryMediaTypes list, the endpoint will receive the JPEG file as binary.

Open to suggestions though.

**Comment by twslankard** [comment]
Ah, dang! It's too bad API Gateway has this limitation, as it really reduces the number of possible use cases. Thanks for the info.

**Comment by melevittfl** [comment]
Hi. I can get this to work with a non-chalice lambda function.

```python
header = { 'Content-type': 'image/png' }
    return {
           'statusCode' : 200,
          'headers': header,
          'body' : base64.b64encode(data).decode("utf-8"),
          'isBase64Encoded': True
     }
```

In the API Gateway, I configure the Settings page with a single Binary Types entry of '*/*' and it works. 

However, using Chalice and code like:
```python
return Response(status_code=200,
                    headers=header,
                    body=response_data
                    )
```
(response_data is a plain old binary sequence)

I've tried setting 
```app.api.binary_types =['*/*']```

And that does set the Settings in API Gateway correctly, but I still get the BadRequest error. 

So, in short, it seems like it should be possible as a non-Chalice Lambda handler can return a binary image to a browser GET.

**Comment by SkySor44** [comment]
I know this is after the fact but I was able to get around it by setting `app.api.binary_types = ['image/*']` in my route. It enables the correct content types and did not trigger the BadRequest error.
