### ISSUE TITLE
Support websockets

### ISSUE THREAD

**Issue by schuyler1d** [awslabs/chalice#394]
API gateway doesn't support websockets, but if you have the power behind the curtain it would be lovely to enable websocket support somehow -- the api-gateway itself could expose the open sockets with IP addresses and expose a way to send to them through the context?

**Comment by stealthycoin** [comment]
Lambda does not currently have the ability to support web sockets so there isn't any way to accomplish this currently. What use case would you have for web sockets that would each be timed out in an unknown amount of time and unable to communicate with other clients?

**Comment by lis186** [comment]
[Amazon API Gateway supports WebSocket APIs today.](https://aws.amazon.com/tw/blogs/compute/announcing-websocket-apis-in-amazon-api-gateway/)

**Comment by armujahid** [comment]
@lis186 related issue https://github.com/aws/chalice/issues/1017 is open.
