### ISSUE TITLE
Features ask

### ISSUE THREAD

**Issue by Segflow** [awslabs/chalice#399]
Hello, we are using Chalice to write our API, and here is some features we thing they will be useful to everyone using chalice.

- When writing a  built-in authorizer, sometimes we want to allow all routes after a successful token verification. Something like `routes=['*'] ` would be very useful, 
- `chalice local` should use the envs set in `config.json`
- Enable authorizers in local mode (very useful when writing built-in authorizers)
- A way to add lambda functions that are not exposed to the API

Those are the main features we are missing in chalice(maybe some are already implemented and we are not aware).

Thanks for the amazing tool.

**Comment by stealthycoin** [comment]
> When writing a built-in authorizer, sometimes we want to allow all routes after a successful token verification. Something like routes=['*'] would be very useful,

I would expect that to work already and would consider it a bug that it doesn't.  Interestingly enough this does work:
`return AuthResponse(routes=[AuthRoute('*', ['*'])], principal_id='user')`

 I will log a bug for this issue. #403

> chalice local should use the envs set in config.json

There is an open pull request for this (#396 ) although it fails codecov.

> Enable authorizers in local mode (very useful when writing built-in authorizers)

I will open a feature request for this: #404

> A way to add lambda functions that are not exposed to the API

Does this do what you want: https://github.com/awslabs/chalice/pull/401 it was just merged in.

**Comment by Segflow** [comment]
`return AuthResponse(routes=[AuthRoute('*', ['*'])], principal_id='user')` 
does not work too
