### ISSUE TITLE
chalice delete

### ISSUE THREAD

**Issue by pauldeden** [awslabs/chalice#40]
I love the simplicity of the chalice CLI, but feel there is one more command to add to complete the feature set.  That is a `chalice delete` (or named something similar) command.

I'm requesting this because `chalice deploy` automatically creates the Lambda function, the API Gateway routes and the IAM policy (and perhaps other things).  It would be difficult for novice users and frustrating for advanced users to have to manually delete all those things themselves especially for failed experiments and hello word trials which the simplicity of the CLI encourages.

**Comment by jamesls** [comment]
I agree.  Marking as feature request.  Thanks for the feedback.

**Comment by JamieCressey** [comment]
Agreed, I personally feel this should be managed by a simple CloudFormation template, that way users have the ability to delete the stack from with the AWS UI too if they so desire, and it can be extended upon for future use however the end-user sees fit.

Kind of relates to #35

**Comment by jong-eatsa** [comment]
+1 This feature should be standard, a [counterpart](https://serverless.com/framework/docs/providers/aws/cli-reference/remove/) to ```serverless remove``` for the serverless framework.

**Comment by jamesls** [comment]
I agree, this is something I'd like to add.  In the meantime, the proposal in https://github.com/awslabs/chalice/issues/183 would make this trivial, we'd just use cloudformation to delete the stack.

**Comment by garethr** [comment]
@jamesls in the meantime do you have a list of the resources that are created, so as to make it easier to delete them manually?
