### ISSUE TITLE
[proposal] Add support for pure lambda functions

### ISSUE THREAD

**Issue by jamesls** [awslabs/chalice#400]
This proposes adding support for plain lambda functions in chalice.  There's several benefits for doing this:

* We'll still manage dependency building for you
* You can use stage support to manage dev/prod stacks
* Auto policy generation
* Chalice manages deployment for you.

The API would use a similar decorator API:

```python
@app.lambda_function()
def my_function(event, context):
    pass

```

When this happens we'll create a lambda function called "my_function" which is a direct pass through to the python function.  You'll have to manage authorizing other roles/services to call this lambda function.  The "complete" lambda function name will follow the same naming patter of `{appname}-{stage}-{py_function_name}`

The `lambda_function()` decorator accepts one arg, an optional `name` argument if you don't want to use the python function name for the `py_function_name` portion.

This partially implements https://github.com/awslabs/chalice/issues/162.  There's still a limitation where you need to have at least one `route()` defined, but this is a limitation I plan on removing in the near future.

**Comment by jamesls** [comment]
Implemented in https://github.com/awslabs/chalice/pull/401

**Comment by rajkunkolienkar** [comment]
Chalice has been really helpful to me, when it comes to deploying Lambda functions. I extensively use AWS Step Functions, I make use of pure Lambda functions all the time. Could we have the planned support for not having to define a route / hook up a deployment with the API Gateway
