### ISSUE TITLE
chalice deploy 0.6.0 isn't recognizing AWS_DEFAULT_PROFILE

### ISSUE THREAD

**Issue by abcondas** [awslabs/chalice#405]
Hi, I'm using chalice 0.6.0 and the chalice deploy command seems to be ignoring the AWS_DEFAULT_PROFILE env variable.  Does chalice support the use of this env variable?  I'm getting a permission denied when the user's profile has access to the resource in question.  Thanks.

**Comment by jamesls** [comment]
I would upgrade to the latest version (1.0.0b1 as of right now) and see if you're still getting this issue.  I've confirmed that `AWS_DEFAULT_PROFILE` is honored in the latest versions of python.

Otherwise if you could share a set of steps that repros the issue I can try it out and see what I get.
