### ISSUE TITLE
chalice deploy does not give link

### ISSUE THREAD

**Issue by koaning** [awslabs/chalice#409]
I'm trying out the chalice tutorial with python3.6 and ... it seems to fail. The deploy command does not give me a link with a function that I could test. 

```
$ pwd
/Users/code/Development/chalicetut/helloworld
$ chalice deploy
Initial creation of lambda function.
Updating IAM policy.
Creating deployment package.
copying /anaconda/bin/python => /Users/code/Development/chalicetut/helloworld/.chalice/venv/bin/python
copying /anaconda/bin/../lib/libpython3.6m.dylib => /Users/code/Development/chalicetut/helloworld/.chalice/venv/lib/libpython3.6m.dylib

```

And thats it. Bummer! The tutorial suggests that I should have gotten a printed url. I think something went wrong even though I get no error. Chalice seems unaware of any url.

```
$ chalice url
Error: Could not find a record of deployed values to chalice stage: 'dev'
$ chalice --version
chalice 0.8.1
```

I don't know what is causing it. But here's my python info. 

```
$ which python
/Users/code/Development/chalicetut/chalice/bin/python
$ python
Python 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:04:09)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by stealthycoin** [comment]
My guess is that anaconda is messing it up. Can you try this in a the most recent version of chalice (1.0.0b1) and if that doesn't work try it again with that same version but inside a virtualenv that was created from anything that isn't anaconda.

**Comment by jamesls** [comment]
Closing out issue.  If you're still seeing this in any of the 1.x versions of chalice, let us know and we'll reopen and take another look.
