### ISSUE TITLE
Using the same function name doesn't give a good error message

### ISSUE THREAD

**Issue by boosh** [awslabs/chalice#425]
I created a function called `users`. Then I accidentally redefined the same function name but for a different route at '/articles'. Chalice didn't deploy this erroneous version, but it didn't print a useful error message, just:
```
Updating IAM policy.
'ARTICLES'
```
It'd be better to provide a more explicit error message for this failure scenario.

**Comment by jamesls** [comment]
What version of chalice are you using?  I remember running into this as well but I can't repro on the latest 1.0.0b1 version:

```python
$ cat app.py
from chalice import Chalice

app = Chalice(app_name='fo')


@app.route('/')
def index():
    return {'foo': 'bar'}


@app.route('/foo')
def index():
    return {'foo': 'bar'}


$ chalice deploy
Initial creation of lambda function.
Creating role
Creating deployment package.
Initiating first time deployment...
Deploying to: dev
https://api.execute-api.us-west-2.amazonaws.com/dev/
$ http https://api.execute-api.us-west-2.amazonaws.com/dev/
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 14
Content-Type: application/json
...

{
    "foo": "bar"
}

```

Can you confirm this still fails on 1.0.0b1?  If so can you give me a code snippet I can try that demonstrates the issue?

**Comment by boosh** [comment]
Yes, my bad. I forgot to install the beta. This applies to 0.10.1
