### ISSUE TITLE
Add support to run locally for development

### ISSUE THREAD

**Issue by fawzyj** [awslabs/chalice#44]
Currently we must run `chalice deploy` to be able to test the code.
It 'll be much nicer if we can run it on local host for development and testing/

**Comment by marvinpinto** [comment]
Duplicate of https://github.com/awslabs/chalice/issues/22 ?

**Comment by fawzyj** [comment]
I think #22 is about running lambda function locally, while chalice is about providing web framework interface to API gateway and lambda integration.

I think that we do not need lambda or api gateway to run locally, we need chalice to have a development mode in which it runs on top of wsgi, more or less like flask.

**Comment by jamesls** [comment]
I think that #22 is about a development mode that runs a local http server so you don't have to `chalice deploy` to test.  Or at least that's how I'm interpreting #22.  Let's consolidate issues and track this feature over in #22.
