### ISSUE TITLE
Python 3.5 or greater support

### ISSUE THREAD

**Issue by denismakogon** [awslabs/chalice#46]
- Make code compatible with python 3.5

- Implement HTTP(s) server using aiohttp

**Comment by JamieCressey** [comment]
Chalice supports the same version of Python as Lambda; 2.7. Although there is an open discussion on supporting Py3 within the CLI; #25 

Part of Chalice's appeal is it being lightweight; perhaps a HTTP server for local dev could be a spin off project? Also being discussed in #44 and #22

**Comment by bobcolner** [comment]
My company is blocked on used lambda at scale until 3.5 is supported.

**Comment by jamesls** [comment]
Closing as dupe, let's track this discussion over at #25.
