### ISSUE TITLE
Support for access control with API Gateway

### ISSUE THREAD

**Issue by zeliard** [awslabs/chalice#47]
Is there any plan to support access control functionalities?
For example, only allowing federated identities to API GW, cognito integration, and so on.
If this is possible currently, I hope there are samples or example codes.

**Comment by JamieCressey** [comment]
There's a feature request for adding authentication support, see #14.

**Comment by jamesls** [comment]
Implemented by @JamieCressey via https://github.com/awslabs/chalice/pull/75.  Try it out and let us know if you have any feedback!
