### ISSUE TITLE
Add support for CloudWatch Event Source

### ISSUE THREAD

**Issue by snuffkingit** [awslabs/chalice#49]
I think Chalice is great framework!

I think following decorators are very useful:
```
@app.cron('0 12 * * ? *')
def index():
    return {"hello": "world"}

@app.rate('5 minutes')
def index():
    return {"hello": "world"}
```
"cron" and "rate" correspond to CloudWatch Events. 
I want to use chalice available in a variety of situations.

**Comment by JamieCressey** [comment]
I think decorators are the ideal method of extending the existing functionality, however I think events are out of scope for this project. Perhaps, like Flask, there could be extensions, via additional projects, to the core Chalice functionality which adds this sort of functionality?

**Comment by gottk** [comment]
Is there by now a decorator available to add cloudwatch events? 
I currently have a lambda service which I would love to trigger via cloudwatch events, 
but do not want to use the client to set it up.

**Comment by jamesls** [comment]
I agree with @JamieCressey on this.  I think this is a really great idea (and I would find this really useful myself), but it's out of scope for this project.  I do like the idea of some sort of extensions, similar to flask, but I'm not exactly sure what that would like right now.

This is something I might take a look at in the future, but I'm going to mark this as out of scope for now.

Thanks for the feedback.
