### ISSUE TITLE
deploy fails using Federated Token authentication

### ISSUE THREAD

**Issue by akash1810** [awslabs/chalice#53]
I'm using temporary AWS tokens via [GetFederationToken](http://docs.aws.amazon.com/STS/latest/APIReference/API_GetFederationToken.html) and as

> You cannot use these credentials to call any IAM APIs.

running `chalice deploy` fails after a `ListRoles` call fails.

> botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the ListRoles operation: The security token included in the request is invalid

Does chalice need to perform this `ListRoles` call?

**Comment by JamieCressey** [comment]
Yes to find the ARN of the role to use:

https://github.com/awslabs/chalice/blob/0c90fd3057e64f4615fd93dccacaf7167e55003f/chalice/deployer.py#L389

Supporting CloudFormation (#35) would negate this as the role ARN could be returned as an output of running the template upon creation.

**Comment by jamesls** [comment]
We now support generating a SAM template with the `chalice package` command, but chalice does need to make various IAM calls to deploy your app.

However, if you have pre-existing roles, you can set `manage_iam_role` to false in your `.chalice/config.json` file as well as the `iam_role_arn` value instructing which ARN chalice should use for the Lambda function.  If you do that chalice will not make calls to IAM for configuring roles.
