### ISSUE TITLE
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://lambda.us-west-1.amazonaws.com/2015-03-31/functions/ayo"

### ISSUE THREAD

**Issue by whatsdis** [awslabs/chalice#57]
Ubuntu 12.04, Python 2.7.3

> chalice deploy

botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/ayylmao"

**Comment by jamesls** [comment]
That error suggests it can't even establish a connection to the lambda endpoint.  Are you able to curl the output?  What happens if you just try to curl the url?  You should get something like this:

```
$ curl -i https://lambda.us-east-1.amazonaws.com/
HTTP/1.1 403 Forbidden
Date: Fri, 29 Jul 2016 17:26:03 GMT
x-amzn-RequestId: 86c55406-55b1-11e6-9293-a584f4f4075f
Content-Length: 127
Connection: keep-alive

<MissingAuthenticationTokenException>
  <Message>Missing Authentication Token</Message>
</MissingAuthenticationTokenException>
```

**Comment by whatsdis** [comment]
I modified the config and no longer get this error.

**Comment by cbleach** [comment]
How did you modify the conifg?

**Comment by manohar2000** [comment]
After you have installed CLI. Use the following command to change the config in cmd
$ aws configure
AWS Access Key ID [None]: "Your_access_key_id"
AWS Secret Access Key [None]: "Your_secret_access_key"
Default region name [None]: "your_zone"
Default output format [None]: json

for more info refer : https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html#cli-quick-configuration
