### ISSUE TITLE
Send post statement to DynamoDB

### ISSUE THREAD

**Issue by gottk** [awslabs/chalice#58]
Hy,

I try to create an API gateway and I would like to store data into a DynamoDB table.
Set up chalice successfully and edited the app.py file.

from chalice import Chalice
import boto3

app = Chalice(app_name='appName')

@app.route('/', methods=['POST'])
def submit_data():

    dynamodb = boto3.resource('dynamodb')
    table = dynamodb.Table('TableName')

    data = app.current_request.json_body

    with table.batch_writer() as batch:
        for image in data['ImageList']:
            batch.put_item(
                Item={
                    'StuffA': {
                        'Item_A': data['Item_A'],
                        'Item_B':    data['Item_B'],
                    },'StuffB': {
                        'Item_C': data['Item_C'],
                        'Item_D':    data['Item_D'],
                    },
                }
            )

    return(Item)

Now if i try to submit a POST request (data which should be stored in DB is provided via JSON.

curl -H 'Content-Type: application/json' -v -d @test.json https://url_provided_by_chalice/dev/

I get the following error message any idea how to get it working? I did check AWS credentials as well.

* Connected to ....... port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /home/.../anaconda3/envs/py27/ssl/cacert.pem
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ....SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=Washington; L=Seattle; O=Amazon.com, Inc.; CN=*.execute-api.ap-southeast-2.amazonaws.com
*  start date: Jun  3 00:00:00 2016 GMT
*  expire date: Jun  4 23:59:59 2017 GMT
*  subjectAltName: host "....." matched cert's "*.execute-api.ap-southeast-2.amazonaws.com"
*  issuer: C=US; O=Symantec Corporation; OU=Symantec Trust Network; CN=Symantec Class 3 Secure Server CA - G4
*  SSL certificate verify ok.
> POST /dev/ HTTP/1.1
> Host: dc8t02jg99.execute-api.ap-southeast-2.amazonaws.com
> User-Agent: curl/7.49.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 301
> 
* upload completely sent off: 301 out of 301 bytes
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< Content-Length: 94
< Connection: keep-alive
< Date: Thu, 21 Jul 2016 04:38:32 GMT
< x-amzn-RequestId:....
< X-Cache: Error from cloudfront
< Via: 1.1 .....cloudfront.net (CloudFront)
< X-Amz-Cf-Id: YoeQ4H6La2w-vnfwUjQkhYYGrnagiHtz8yaW4sRk4n3XpX_9mwLHxA==
< 
* Connection #0 to host .....execute-api.ap-southeast-2.amazonaws.com left intact
{"Code": "ChaliceViewError","Message": "ChaliceViewError: An internal server error occurred."}

Any kind of help is appreciated!

Cheers

**Comment by jamesls** [comment]
It might an issue with the policy being used.  The thing I would suggest is to do add `app.debug = True` after the `app = Chalice(app_name='appName')` line.  This will print additional debugging information.  Once you share that, that will help troubleshoot further.

**Comment by gottk** [comment]
Thanks Jamesls,

I figured it out just yesterday, the problem was, that obviously the IAM role has been created automatically. I had to manually adapt the policy.json file, so permission is granted to post items into the database.

**Comment by gottk** [comment]
Thanks Jamesls,

I figured it out just yesterday, the problem was, that obviously the IAM role has been created automatically. I had to manually adapt the policy.json file, so permission is granted to post items into the database.
