### ISSUE TITLE
make IAM configurable

### ISSUE THREAD

**Issue by sdole** [awslabs/chalice#61]
Running chalice deploy attempts to create a IAM role of the name of the application. Unfortunately, in my enterprise, not all AWS developers are allowed to create an IAM role for security best practices reasons. The entire IAM roles and policy thing should be configurable so that an IAM admin can create the required role/policy beforehand and grant use of it to developers.

**Comment by sdole** [comment]
see pull #62

**Comment by jamesls** [comment]
Thanks for the feature request.  I think this would be good to add.  I'll take a look at your pull request soon.

**Comment by sdole** [comment]
You are welcome. Let me know if you have questions or if you want me to try a different design/approach.

**Comment by jamesls** [comment]
Fixed via https://github.com/awslabs/chalice/pull/85.  Thanks again for the pull request.
