### ISSUE TITLE
Apply scheduler on lambda service

### ISSUE THREAD

**Issue by gottk** [awslabs/chalice#86]
Is there a possibility to apply a schedule on the lambda services created with chalice?

It would be great if things like that would work - Unfortunately, it does not work, 
yet, when adding a schedule via the AWS interface (Triggers - CloudWatchEvents Schedule)

cheers

**Comment by jamesls** [comment]
This was previously discussed at https://github.com/awslabs/chalice/issues/49, which for now is out of scope of this project.

I think if there's enough interest, it's something I'd reconsider, but right now the focus is on creating rest APIs with API gateway and Lamba.
