### ISSUE TITLE
Error: Error when deploying: Could not connect to the endpoint URL:

### ISSUE THREAD

**Issue by loretoparisi** [awslabs/chalice#89]
Hi,
I have setup the `~/.aws/config` credentials file with active credentials.
When trying to deploy the demo app I get the error 

Error: Error when deploying: Could not connect to the endpoint URL:
`https://lambda.us-east-1a.amazonaws.com/2015-03-31/functions/chalice-demo`

**Comment by jamesls** [comment]
It looks like you have a region of `us-east-1a` configured, and it should be `us-east-1`.  `us-east-1a` is an availability zone.

Make sure in `~/.aws/config` you have:

```
[default]
region = us-east-1
```

Let me know if you're still having issues and I'll reopen and take another look.

**Comment by loretoparisi** [comment]
@jamesls right that's true I've copied&paste from aws console the availability zone! Successfully deployed to `us-east-1`.
