### ISSUE TITLE
I want to use "IAM User signature" authorization_type.

### ISSUE THREAD

**Issue by minhoryang** [awslabs/chalice#93]
According to #14, I want to use "IAM User signature" authorization_type.
Which type should I write for it.

``` python
authorization_type='IAM'  # ?
```

**Comment by byumark** [comment]
+1

**Comment by 3dw1np** [comment]
+1

**Comment by kadrach** [comment]
Not tested, but [this document](http://docs.aws.amazon.com/apigateway/latest/developerguide/permissions.html) says

> The API developer sets the method's authorizationType property to **AWS_IAM** to require that the caller submit the IAM user's access keys to be authenticated.

**Comment by 3dw1np** [comment]
Thanks, I confirm it works 👍 
@app.route('/users', methods=['POST'], authorization_type='AWS_IAM', cors=True)

**Comment by jamesls** [comment]
https://github.com/awslabs/chalice/pull/334 has been merged which adds support for IAM authorization.  Let me know if you have any questions/concerns.
