### ISSUE TITLE
option to enable CORS

### ISSUE THREAD

**Issue by sdole** [awslabs/chalice#97]
I need to enable CORS on my api. Is there any way to do it in Chalice?

**Comment by b-b3rn4rd** [comment]
does not look like, https://github.com/awslabs/chalice/blob/master/chalice/deployer.py#L600, definitely would be handy to have

**Comment by jamesls** [comment]
Not yet, but I plan on adding it.  There's a tracking issue here: https://github.com/awslabs/chalice/issues/70

Closing as dupe, let's continue the conversation over on #70.
