### ISSUE TITLE
separation of chalice app and chalice deploy concerns?

### ISSUE THREAD

**Issue by sdole** [awslabs/chalice#98]
I wonder if I am the only one feeling this... but, i feel like Chalice - the bridge between lambda and flask and Chalice - the api gateway deployer are two separate concerns. I would have liked to be able to use the bridge by itself and use my own ways to deploy.

**Comment by jamesls** [comment]
Just curious, what are some of the specific ways you want to deploy that are different from how it's done now?

I'm interested to learn more, but I would also like to see if there's any general improvements to `chalice deploy` that would make sense to move directly into project.

**Comment by pouledodue** [comment]
@sdole you may want to look at the serverless.com project..

**Comment by sdole** [comment]
I use cloudformation (and swagger) to deploy lambda/api gateway. I also have a small python script that deals with automating this (so that parameters can be passed to cloudformation template via a yaml file).

I guess since chalice is new, the code to do all of the things that cloudformation already does will need some coding. In other words, chalice may become full featured as time goes by. Until then, it will be nice to just use the "bridge" (as i called it) and deploy on my own.

I dont mean to suggest that chalice is not good...

**Comment by jamesls** [comment]
@sdole, I've created a proposal to use cfn/SAM as a new deployment backend: https://github.com/awslabs/chalice/issues/183

Would this address your concern?  Feel free to comment on the issue with any feedback you have.

**Comment by pearceshaun** [comment]
@jamesls I'd love to see cfn/SAM support. Like @sdole we have also invested in our own CloudFormation deployment stack for both Lambda functions as well as EC2 based microservices. Being able to use the Chalice programming framework but then deploying the resulting package through CFN would be really helpful!

**Comment by sdole** [comment]
@jamesls I read #183 and it looks great! So, as I am understanding it, it will continue to use chalice's ability to reflect on the flask code and determine apis. Next step, if the user so chooses, chalice can package into a SAM and cloudformation package. Finally it can also deploy if requested. 

I like it. I am available to work on it if you would like me to. Should I?

**Comment by jamesls** [comment]
Closing out old issue, this is now possible using the `chalice package` command which will generate the deployment zip file and a SAM template (which also embeds the swagger document for your API).  You can now use the CLI/whatever CFN deployment tools you've written to deploy your app.
